"""The 70 mails as they will be after the rewrite: subject, preheader, blocks, and what changes.

Block vocabulary (see mail_theme.py): title, p, small, details, credentials, code, action,
outline, linkline, notice, list, steps, table, internal, signature.

status: rewritten  - copy and structure changed
        restyled   - same content, poured into the shell
        converted  - was plain text, now a themed mail
        wrapped    - admin-authored content, wrapped in the shell by the dispatcher
        deleted    - no caller, or retired; removed rather than restyled
        merged     - retired because another mail already says the same thing
"""

HI = ("p", "Hi {{first_name}},")
HI_C = ("p", "Hi {{counsellor_name}},")
SIG = ("signature",)
EARLY = ("small", "Please join a few minutes before the start time.")
KEEP = ("small", "Keep these details safe. You will need them to resume the assessment and to open your report later.")
CREDS = ("credentials", [("Username", "{{username}}"), ("Password", "{{password}}")], "Your password is your date of birth, DD-MM-YYYY.")
SESSION_ROWS = [("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Counsellor", "{{counsellor_name}}"), ("Mode", "{{session_mode}}")]

SPECS = [
# ── Registration & login ───────────────────────────────────────────────────────
dict(id="login-credentials", status="rewritten",
     subject="Your {{school_name}} login details",
     pre="Username and password to sign in and take your assessment.",
     blocks=[("title", "Your login details"), HI,
             ("p", "Use the details below to sign in and take your assessment. You can pause and resume at any time."),
             CREDS,
             ("steps", [("Sign in", "Open the portal with the button below and enter the details above."),
                        ("Complete your assessment", "Pick the assessment assigned to you and answer honestly. There are no right or wrong answers."),
                        ("Get your report", "Once you submit, your Career Report is built across six career dimensions and appears in your dashboard.")]),
             ("action", "dashboard_link", "Sign in"), KEEP, SIG],
     changes=["Teal glass card, gradient heading and key icon replaced by the shell.",
              "\"Hello, Aarav!\" becomes \"Hi Aarav,\"; button \"Log In Now\" becomes \"Sign in\".",
              "The seeded admin template is updated by migration only if it is still the seeded default; an edited template is left alone and wrapped in the shell at send time.",
              "Placeholders email_header and email_footer are retired (the shell provides both)."]),
dict(id="school-registration-success", status="rewritten",
     subject="You're registered for {{assessment_name}}",
     pre="Your username and password are inside. Sign in when you're ready.",
     blocks=[("title", "Registration successful"), HI,
             ("p", "You are registered for <b>{{assessment_name}}</b>. Sign in with the details below when you are ready to begin."),
             CREDS, ("action", "login_link", "Sign in"), KEEP, SIG],
     changes=["Green gradient header card replaced by the shell.",
              "Hardcoded https://assessment.career-9.com/ replaced by LinkBuilder.manualLogin(), so staging mails stop pointing at production.",
              "\"Dear <strong>name</strong>\" becomes \"Hi name,\"; the \"automated email, do not reply\" line goes (footer covers it).",
              "Same builder now serves the assessment-mapping registration mail below."]),
dict(id="mapping-registration-success", status="rewritten",
     subject="You're registered for {{assessment_name}}",
     pre="Your username and password are inside. Sign in when you're ready.",
     blocks=[("title", "Registration successful"), HI,
             ("p", "You are registered for <b>{{assessment_name}}</b>. Sign in with the details below when you are ready to begin."),
             CREDS, ("action", "login_link", "Sign in"), KEEP, SIG],
     changes=["Purple gradient header replaced by the shell; this mail and the school-registration one become a single builder.",
              "Name, assessment, username and DOB were interpolated unescaped; the blocks escape them.",
              "Hardcoded https://assessment.career-9.com/ replaced by LinkBuilder."]),
dict(id="account-welcome", status="converted",
     subject="Welcome to Career-9",
     pre="Your account is under review. We will let you know once it is active.",
     blocks=[("title", "Welcome to Career-9"), HI,
             ("p", "Thanks for registering. Your account is under review and we will email you as soon as it is active."), SIG],
     changes=["Plain text becomes a themed mail with a plain-text part.",
              "The \"review.We\" typo goes. No button: there is nothing to do until the account is approved."]),
dict(id="password-reset-link", status="restyled",
     subject="Reset your Career-9 password",
     pre="This link works once and expires in {{reset_minutes}} minutes.",
     blocks=[("title", "Reset your password"), HI,
             ("p", "We received a request to reset the password for your Career-9 account. Use the button below to choose a new one. The link works once and expires in <b>{{reset_minutes}} minutes</b>."),
             ("action", "reset_link", "Reset password"),
             ("small", "If you did not request this, you can ignore this email. Your password stays as it is."), SIG],
     changes=["Blue #009ef7 button becomes the green house button.",
              "The full reset URL printed under the button becomes a short link.",
              "\"— The Career-9 Team\" becomes the standard sign-off; preheader added."]),
dict(id="password-reset-confirm", status="restyled",
     subject="Your Career-9 password was changed",
     pre="If this wasn't you, secure your account now.",
     blocks=[("title", "Your password was changed"), HI,
             ("p", "The password for your Career-9 account was just changed."),
             ("notice", "If this wasn't you, reset your password again straight away and write to support@career-9.net so we can check the account."),
             ("action", "dashboard_link", "Sign in"), SIG],
     changes=["Unstyled div becomes the shell.",
              "\"Contact support immediately\" now names the address; a sign-in button is added."]),
dict(id="admin-password-reset", status="converted",
     subject="Your Career-9 password has been reset",
     pre="An administrator set a new password for you. Change it after signing in.",
     blocks=[("title", "Your password has been reset"), HI,
             ("p", "An administrator has reset the password for your Career-9 account."),
             ("credentials", [("New password", "{{new_password}}")], "Sign in with your registered email and this password, then change it from your profile."),
             ("action", "dashboard_link", "Sign in"),
             ("small", "If you did not ask for this change, contact your administrator or write to support@career-9.net."), SIG],
     changes=["Plain text becomes a themed mail.",
              "Hardcoded https://dashboard.career-9.com replaced by config.",
              "The plaintext password stays (existing product decision) but sits in the credentials panel, never in the subject."]),
dict(id="account-activated", status="converted",
     subject="Your Career-9 account is active",
     pre="You can sign in now with your registered email and password.",
     blocks=[("title", "Your account is active"), HI,
             ("p", "Your Career-9 dashboard account has been activated. Sign in with your registered email and password."),
             ("action", "dashboard_link", "Sign in"), SIG],
     changes=["Plain text becomes a themed mail; \"Congratulations!\" subject dropped.",
              "Hardcoded https://dashboard.career-9.com replaced by config.",
              "Behaviour fix: today this mail also fires on deactivation. It will be sent only when the account is activated."]),

# ── Payments ───────────────────────────────────────────────────────────────────
dict(id="payment-success-welcome", status="rewritten",
     subject="Payment received for {{assessment_name}}",
     pre="Your assessment is ready. Username and password are inside.",
     blocks=[("title", "Payment received"), HI,
             ("p", "Your payment for <b>{{assessment_name}}</b> has been received and the assessment is ready for you."),
             CREDS, ("action", "login_link", "Start assessment"), KEEP, SIG],
     changes=["Green gradient header replaced by the shell; \"Payment Successful!\" becomes \"Payment received\".",
              "Hardcoded https://assessment.career-9.com/ replaced by LinkBuilder.",
              "\"Dear <strong>name</strong>\" becomes \"Hi name,\"; do-not-reply line removed."]),
dict(id="payment-success-resend", status="rewritten",
     subject="Your {{assessment_name}} is ready",
     pre="One tap starts your assessment. Your username and password are inside for later.",
     blocks=[("title", "Your assessment is ready"), HI,
             ("p", "Your payment for <b>{{assessment_name}}</b> was received and the assessment is waiting for you. You can pause and resume at any time."),
             ("p", "One tap signs you in and takes you straight to your assessment:"),
             ("action", "assessment_link", "Start assessment"),
             ("p", "<b>Or sign in manually</b> with:"),
             CREDS,
             ("linkline", [("login_link", "Open the sign-in page")]),
             KEEP, SIG],
     changes=["Gradient header replaced by the shell; subject loses the exclamation mark.",
              "Now carries the student's username and date of birth, which the current resend omits.",
              "Adds the one-tap magic link (the entitlement's access token, shortened). For a legacy school or mapping payment with no entitlement there is no token, so the primary button becomes \"Sign in\" to the sign-in page and the credentials panel stays.",
              "Hardcoded host replaced by LinkBuilder."]),
dict(id="payment-failed-cancelled-expired", status="rewritten",
     subject="Payment for {{assessment_name}} did not go through",
     pre="Nothing has been charged. Use the button to try again.",
     blocks=[("title", "Payment could not be completed"), HI,
             ("p", "Your payment of <b>&#8377;{{amount}}</b> for <b>{{assessment_name}}</b> did not go through, so nothing has been charged."),
             ("notice", "If an amount was deducted from your account, it will be refunded automatically within 5&ndash;7 working days."),
             ("action", "payment_link", "Try again"), SIG],
     changes=["Three coloured gradient headers (red, slate, pink) collapse into one shell; the variant lives in the subject and first line only: \"did not go through\" / \"link has expired\" / \"was cancelled\".",
              "Indigo gradient \"Retry Payment\" button becomes the green house button; the retry URL goes through the short-link service.",
              "\"INR 1499\" becomes \"₹1,499\"."]),
dict(id="payment-pending-nudge", status="rewritten",
     subject="Complete your payment for {{assessment_name}}",
     pre="₹{{amount}} is still pending. The button takes you straight to payment.",
     blocks=[("title", "Your payment is still pending"), HI,
             ("p", "Your payment of <b>&#8377;{{amount}}</b> for <b>{{assessment_name}}</b> is still pending. Complete it to get access to your assessment."),
             ("action", "payment_link", "Complete payment"), SIG],
     changes=["Amber gradient header and amber button become the shell and green button.",
              "\"Automated reminder, do not reply\" removed."]),
dict(id="payment-link", status="rewritten",
     subject="Payment link for {{assessment_name}}",
     pre="₹{{amount}} for {{assessment_name}}. Pay securely with the button below.",
     blocks=[("title", "Your payment link"), HI,
             ("p", "Here is your payment link for <b>{{assessment_name}}</b>. The amount due is <b>&#8377;{{amount}}</b>."),
             ("action", "payment_link", "Pay now"),
             ("small", "Payments are processed securely by Razorpay."), SIG],
     changes=["Indigo gradient header and button become the shell and green button.",
              "\"Or copy this link: <full URL>\" becomes the short link under the button."]),

# ── Assessment & reports ───────────────────────────────────────────────────────
dict(id="assessment-completion", status="rewritten",
     subject="You've completed {{assessment_name}}",
     pre="Your report is being prepared. Here is what happens next.",
     blocks=[("title", "Assessment complete &#10003;"), HI,
             ("p", "Great work. You have completed <b>{{assessment_name}}</b>."),
             ("credentials", [("Username", "{{username}}"), ("DOB", "{{password}}")], "Use these to sign in to your dashboard."),
             ("steps", [("Your report is being generated", "Your responses are being analysed across six career dimensions to build your personalised Career Report."),
                        ("Check your dashboard", "Sign in to see your career matches, strengths and detailed insights once the report is ready."),
                        ("Talk to a career expert", "Book a session from your dashboard any time to go through your results with a counsellor.")]),
             ("action", "dashboard_link", "Go to my dashboard"), SIG],
     changes=["Teal glass card and gradient heading replaced by the shell; the ✓ stays.",
              "Hardcoded https://dashboard.career-9.com/student/login replaced by LinkBuilder.",
              "Credentials panel still appears only when a username or DOB is available."]),
dict(id="report-ready-pipeline", status="restyled",
     subject="Your {{school_name}} report is ready",
     pre="Your personalised report is ready to read. Open it from this email.",
     blocks=[("title", "&#127881; Your career assessment is complete"),
             ("p", "Hi {{first_name}}, now comes the exciting part&hellip;"),
             ("list", ["&#128269; What does your report say about <b>you</b>?", "&#128161; What are your natural strengths?",
                       "&#127919; Which careers match your personality and abilities?", "&#128640; What could you work on to get closer to your goals?"]),
             ("p", "Your personalised <b>{{school_name}} Report</b> is ready, filled with insights about your strengths, interests, abilities and career possibilities."),
             ("action", "report_link", "View my report"),
             ("linkline", [("report_pdf_link", "Download as PDF")], "Your detailed report is also attached to this email as a PDF."),
             ("p", "But remember, the report is just the beginning &#127775;"),
             ("p", "<b>&#128640; Your next step.</b> Now it&rsquo;s time to understand what these insights mean for your future. Get your report interpreted by an expert in a 1:1 online session:"),
             ("list", ["&#10024; Explore career options that fit <b>you</b>", "&#10024; Discover your strengths and improvement areas",
                       "&#10024; Get clarity on your next academic step", "&#10024; Ask anything about your future. No question is too small"]),
             ("outline", "booking_link", "Book my counselling session"),
             ("p", "Your future is not a guess. It&rsquo;s a journey, and {{school_name}} is here to help you navigate it."), SIG],
     changes=["C9 badge header and bare footer replaced by the shell; every emoji stays.",
              "\"Download as PDF\" becomes a labelled link; the booking button stays an outline button and still appears only when the student is eligible.",
              "Same body serves the admin resend below."]),
dict(id="final-report-link-resend", status="merged",
     changes=["Retired. It was the same body as \"Report ready\" with a different sender path.",
              "The admin resend (POST /entitlement/{id}/resend/final_report) and the pipeline-disabled immediate send now go through the Report ready mail, so there is exactly one report mail.",
              "Idempotency for the automatic runs (no duplicate report mails on retries or re-queues) is phase 2."]),
dict(id="one-pager-ready", status="deleted",
     changes=["Retired. The 1-pager is no longer sent from anywhere.",
              "EntitlementService.onAssessmentCompleted stops mailing tiers without the final report; those students get nothing by mail at completion (the assessment-completion mail still goes out)."]),
dict(id="one-pager-resend", status="deleted",
     changes=["Retired with the 1-pager. The one_pager case of the admin resend endpoint is removed."]),
dict(id="contact-person-report-email", status="wrapped", cta_optional=True,
     subject="{{subject}}",
     pre="{{body_excerpt}}",
     blocks=[("p", "{{body}}")],
     changes=["Content stays exactly what the admin composes; the dispatcher wraps it in the shell.",
              "Any link over 60 characters inside the admin's HTML is shortened by the dispatcher before sending.",
              "The preheader is the first 90 characters of the message."]),
dict(id="contact-person-reports-zip", status="rewritten", cta_optional=True,
     subject="{{report_type}} reports: {{institute_name}}",
     pre="{{report_count}} student reports for {{assessment_name}} are attached as a ZIP.",
     blocks=[("title", "Student reports attached"), ("p", "Hi {{contact_name}},"),
             ("p", "The <b>{{report_type}}</b> reports for <b>{{assessment_name}}</b> are attached as a ZIP file. Extract it to open each student&rsquo;s report."),
             ("details", [("School", "{{institute_name}}"), ("Assessment", "{{assessment_name}}"), ("Report type", "{{report_type}}"), ("Reports included", "{{report_count}} students")]),
             ("table", ["#", "Student"], [["1", "Aarav Sharma"], ["2", "Diya Patel"], ["3", "Kabir Rao"]]),
             ("notice", "{{no_report_count}} students do not have a generated report yet and are not included."),
             SIG],
     changes=["Navy gradient banner with \"Ensuring Career Success\" replaced by the shell (the tagline now lives in the footer).",
              "Contact name, school and student names were interpolated unescaped; the blocks escape them.",
              "Hardcoded support@career-9.com and phone number removed; the footer carries the support address from config.",
              "Subject shortened from \"Navigator Reports | Assessment | School – Career-9\"."]),
dict(id="school-dashboard-ready", status="restyled",
     subject="Your school dashboard is ready: {{institute_name}}",
     pre="Insights from {{assessment_name}} across your students are live.",
     blocks=[("title", "Your school dashboard is live"), ("p", "Hi {{contact_name}},"),
             ("p", "The Career-9 school dashboard for <b>{{institute_name}}</b> is now live. It summarises what <b>{{assessment_name}}</b> found across your students: where they are heading, where they will need support, and what the school can do about it."),
             ("action", "school_dashboard_link", "Open your dashboard"),
             ("steps", [("Sign in", "Use the account we set up for you, then choose Reports &rarr; School Dashboard from the menu on the left."),
                        ("Filter", "The page opens on the whole school. The filters at the top narrow it to a grade, section or group; figures and written analysis both change to match."),
                        ("Start at the top", "The statement and the three cards under it are the findings we think need action first. The full analysis below explains each one with the figures it is based on.")]),
             ("notice", "Every figure comes from students who completed and were scored on the assessment. Cohorts too small to describe safely are left without written analysis on purpose."),
             ("small", "If a figure looks off, a class is missing, or the page will not open, write to support@career-9.net with the school name and the grade or section you were viewing."),
             SIG],
     changes=["Unstyled div becomes the shell; blue #1c5cab button becomes green.",
              "\"Reply to this email\" becomes \"write to support@career-9.net\"."]),
dict(id="counsellor-report-ready", status="restyled",
     subject="Report ready: {{student_name}}",
     pre="{{student_name}} has finished {{assessment_name}}. Read it before your session.",
     blocks=[("title", "Report ready: {{student_name}}"), HI_C,
             ("p", "<b>{{student_name}}</b> has completed <b>{{assessment_name}}</b> and the report is ready."),
             ("action", "report_link", "Open report"),
             ("small", "Please look through it before your session so you can go straight to what matters."), SIG],
     changes=["Counselling house style becomes the shell.",
              "The full report URL printed under the button becomes a short link; \"Hello,\" becomes a named greeting."]),
dict(id="booked-session-report-ready", status="restyled",
     subject="Report ready for your counselling session",
     pre="{{student_name}}'s report is ready ahead of the session on {{session_date}}.",
     blocks=[("title", "Assessment report ready"), ("p", "Hello,"),
             ("p", "The assessment report for <b>{{student_name}}</b> is now ready, ahead of the counselling session on <b>{{session_date}}</b>."),
             ("action", "report_link", "Open report"),
             ("small", "Please read it before the session so the time can be spent on what matters most."), SIG],
     changes=["Counselling house style becomes the shell; short link under the button.",
              "\"Hello,\" stays because the same mail goes to the student, the parent and the counsellor."]),
dict(id="counsellor-report-release", status="restyled",
     subject="Your assessment report is ready",
     pre="Released by {{released_by}} after your counselling session.",
     blocks=[("title", "Your assessment report is ready"), HI,
             ("p", "Your assessment report has been released by <b>{{released_by}}</b> following your counselling session."),
             ("action", "report_link", "Open my report"),
             ("small", "Take your time with it, and come back to your counsellor with anything you would like explained further."), SIG],
     changes=["Counselling house style becomes the shell; short link under the button; \"Dear\" becomes \"Hi\"."]),
dict(id="reminder-assessment-mapping", status="rewritten",
     subject="Reminder: complete {{assessment_name}}",
     pre="Your assessment from {{institute_name}} is waiting for you.",
     blocks=[("title", "Your assessment is waiting"), HI,
             ("p", "You have an assessment, <b>{{assessment_name}}</b>, assigned by <b>{{institute_name}}</b> that you have not started yet. Complete it when you have 30&ndash;40 quiet minutes."),
             ("action", "login_link", "Start my assessment"), SIG],
     changes=["Bare paragraphs from reminder_config become a themed mail: the dispatcher wraps reminder bodies in the shell, and the seeded row is updated by migration if it is still the seed.",
              "The raw {{link}} line goes. Today that placeholder is never populated and assessmentName renders as \"Assessment #12\"; the rewrite passes the real name and the sign-in page.",
              "Admins keep editing this text on the Reminder Management page; only the shell is fixed."]),
dict(id="reminder-assessment-invite-b2c-template", status="rewritten",
     subject="Reminder: complete your career assessment",
     pre="Your {{assessment_name}} is waiting. Start it with one tap.",
     blocks=[("title", "Your assessment is waiting"), HI,
             ("p", "You have not started <b>{{assessment_name}}</b> yet. It takes 30&ndash;40 minutes and you can pause and resume."),
             ("action", "assessment_link", "Start my assessment"), SIG],
     changes=["Bare paragraphs become a themed mail; the raw {{link}} line becomes a button with a short link."]),
dict(id="reminder-counselling-24h-template", status="rewritten",
     subject="Your counselling session is tomorrow",
     pre="{{session_time}} with {{counsellor_name}}. Join link inside.",
     blocks=[("title", "Your counselling session is tomorrow"), HI,
             ("p", "Your session with <b>{{counsellor_name}}</b> is scheduled for <b>{{session_date}}, {{session_time}}</b>."),
             ("details", [("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Counsellor", "{{counsellor_name}}")]),
             ("action", "join_link", "Join the session"),
             ("small", "The link becomes active 10 minutes before the start."), SIG],
     changes=["Bare paragraphs become a themed mail; \"Join here: <URL>\" becomes a button."]),
dict(id="reminder-counselling-1h-template", status="rewritten",
     subject="Your counselling session starts in an hour",
     pre="Starts at {{session_time}}. Join link inside.",
     blocks=[("title", "Your session starts in an hour"), HI,
             ("p", "Your counselling session starts at <b>{{session_time}}</b>."),
             ("action", "join_link", "Join the session"),
             ("small", "Join a few minutes early so the session can start on time."), SIG],
     changes=["Bare paragraphs become a themed mail; \"Join here: <URL>\" becomes a button."]),

# ── Campaign / B2C ─────────────────────────────────────────────────────────────
dict(id="b2c-welcome-assessment-link", status="restyled",
     subject="Welcome to Career-9: start your assessment",
     pre="One tap signs you in. Your username and password are inside for later.",
     blocks=[("title", "Welcome aboard, {{first_name}}"),
             ("p", "Your purchase is confirmed and your assessment is ready when you are. You can pause and resume at any time."),
             ("p", "One tap signs you in and takes you straight to your assessment:"),
             ("action", "assessment_link", "Start assessment"),
             ("p", "<b>Or sign in manually</b> with:"),
             CREDS,
             ("linkline", [("login_link", "Open the sign-in page")]),
             ("small", "Keep these safe. You will need them to resume your assessment or open your report later."), SIG],
     changes=["Green flat card becomes the shell.",
              "\"If the button doesn't work, paste this link: <140-character magic link>\" becomes the short link under the button.",
              "The manual sign-in URL becomes a labelled link."]),
dict(id="b2c-assessment-invite-resend", status="rewritten",
     subject="Your Career-9 assessment link",
     pre="Your assessment is waiting. One tap to start or resume.",
     blocks=[("title", "Your assessment link"), HI,
             ("p", "Here is your link to <b>{{assessment_name}}</b>. One tap signs you in, and you can pause and resume at any time."),
             ("action", "assessment_link", "Start assessment"), SIG],
     changes=["Navy gradient header becomes the shell; raw link removed; greeting and assessment name added.",
              "Behaviour note: the hourly nudge cap counts the wrong log type today, so it never trips. The rewrite logs nudges under their own type."]),
dict(id="b2c-dashboard-access", status="rewritten",
     subject="Your Career-9 dashboard access",
     pre="One tap opens your dashboard.",
     blocks=[("title", "Your dashboard access"), HI,
             ("p", "One tap below signs you in and opens your Career-9 dashboard, where your results and next steps live."),
             ("action", "dashboard_sso_link", "Open my dashboard"),
             ("small", "The link is personal to you. Please don&rsquo;t forward it."), SIG],
     changes=["Navy gradient header becomes the shell; \"Click below:\" and the raw link go."]),
dict(id="b2c-lms-access", status="rewritten",
     subject="Your Career-9 learning access",
     pre="Your learning modules are ready.",
     blocks=[("title", "Your learning modules are ready"), HI,
             ("p", "Your Career-9 learning modules are ready. One tap below signs you in and opens them."),
             ("action", "lms_link", "Open my modules"),
             ("small", "The link is personal to you. Please don&rsquo;t forward it."), SIG],
     changes=["Navy gradient header becomes the shell; \"LMS\" becomes \"learning modules\" for students; raw link removed."]),
dict(id="b2c-counselling-book-link", status="rewritten",
     subject="Book your Career-9 counselling session",
     pre="Pick a time that suits you. No login needed.",
     blocks=[("title", "Book your counselling session"), HI,
             ("p", "Your plan includes a one-to-one counselling session. Pick a time that suits you; no login is needed."),
             ("action", "booking_link", "Book my session"),
             ("small", "Once you choose a slot, your session is confirmed instantly and you will receive the meeting details by email."), SIG],
     changes=["Navy gradient header becomes the shell; raw link removed.",
              "Behaviour note: the 10:30 scheduler sends this and the booking-nudge mail in the same run; the rewrite sends one."]),

# ── Admin & internal ───────────────────────────────────────────────────────────
dict(id="lead-notification", status="rewritten",
     subject="New {{lead_type}} lead: {{lead_name}}",
     pre="{{lead_source}} · received {{lead_received_at}}",
     blocks=[("internal", "New lead alert"), ("title", "New enquiry from the website"),
             ("p", "<b>{{lead_type}}</b> &middot; {{lead_source}} &middot; received {{lead_received_at}}"),
             ("details", [("Name", "{{lead_name}}"), ("Email", "{{lead_email}}"), ("Phone", "{{lead_phone}}"), ("School", "{{lead_school}}"), ("City", "{{lead_city}}"), ("Designation", "{{lead_designation}}")]),
             ("action", "admin_leads_link", "Open lead #{{lead_id}}"),
             ("small", "Every field the form submitted is listed above. This alert goes to everyone on the New-lead recipient list; change it under Email &rsaquo; Notification recipients.")],
     changes=["Bare div becomes the shell with an Internal tag.",
              "\"Reply to Rohan\" mailto button becomes a button to the lead in the admin app; replies happen from there.",
              "The seeded admin template is migrated if unchanged; an edited one is wrapped in the shell."]),
dict(id="leads-email-export", status="wrapped", cta_optional=True,
     subject="{{subject}}",
     pre="{{body_excerpt}}",
     blocks=[("internal", "Leads export"), ("p", "{{body}}")],
     changes=["Admin-typed body wrapped in the shell; the Excel attachment is unchanged."]),
dict(id="generic-send-with-attachment", status="wrapped", cta_optional=True,
     subject="{{subject}}",
     pre="{{body_excerpt}}",
     blocks=[("p", "{{body}}")],
     changes=["Admin-typed body wrapped in the shell; the attachment is unchanged."]),
dict(id="email-account-test", status="converted", cta_optional=True,
     subject="Career-9 email test: {{account_name}}",
     pre="If you can read this, the account can send.",
     blocks=[("internal", "Email account test"), ("title", "This account can send"),
             ("p", "This is a test email from Career-9 confirming that the <b>{{account_name}}</b> account ({{provider}}) can send mail."),
             ("details", [("Account", "{{account_name}}"), ("Provider", "{{provider}}"), ("Sent", "{{sent_at}}")])],
     changes=["One bare paragraph becomes a themed mail, so the test also proves the logo loads through that account."]),
dict(id="email-template-test", status="wrapped", cta_optional=True,
     subject="{{subject}}",
     pre="{{body_excerpt}}",
     blocks=[("internal", "Template test with sample values"), ("p", "{{body}}")],
     changes=["The chosen template renders inside the shell exactly as a real send would."]),
dict(id="counselling-block-date-request", status="deleted", changes=["Defined but never called (block-date requests are handled in-app). Deleted."]),
dict(id="counsellor-deactivated-admin-alert", status="restyled",
     subject="Counsellor deactivated: {{counsellor_name}} ({{affected_count}} sessions)",
     pre="{{affected_count}} sessions taken off the calendar. Some students need a follow-up.",
     blocks=[("internal", "Counsellor deactivation"), ("title", "Counsellor deactivated"),
             ("details", [("Counsellor", "{{counsellor_name}}"), ("Email", "{{counsellor_email}}"), ("Deactivated by", "{{admin_name}}"), ("Sessions affected", "{{affected_count}}")]),
             ("p", "The students below have had their session taken off the calendar. <b>Rebooking link sent</b> means they can pick a new time themselves. <b>Needs follow-up</b> means no other counsellor covers their assessment and they were told the team would be in touch."),
             ("table", ["Student", "When", "Contact", "Outcome"],
              [["Aarav Sharma", "18 Sep, 4:30 PM", "aarav@example.com &middot; 98765 43210", "Rebooking link sent"],
               ["Diya Patel", "19 Sep, 11:00 AM", "diya@example.com &middot; 98111 22334", "Needs follow-up"],
               ["Kabir Rao", "20 Sep, 3:00 PM", "kabir@example.com &middot; 99887 76655", "Rebooking link sent"]]),
             ("action", "admin_sessions_link", "Open Manage Sessions")],
     changes=["Counselling house style becomes the shell with an Internal tag; student rows become a table.",
              "Bug fix: the send is logged under COUNSELLOR_DEACTIVATED_ALERT (its own type) instead of COUNSELLING_NOTIFICATION."]),
dict(id="counselling-request-forwarded", status="restyled",
     subject="Counselling request: {{assessment_name}}",
     pre="A student asked for counselling but no counsellor is mapped to this assessment.",
     blocks=[("internal", "Support inbox"), ("title", "Counselling request needs a counsellor"),
             ("p", "A student has requested career counselling, but no counsellor is mapped to this assessment yet."),
             ("details", [("Assessment", "{{assessment_name}}"), ("Student", "{{student_name}}"), ("Email", "{{student_email}}"), ("Phone", "{{student_phone}}"), ("Institute", "{{institute_name}}")]),
             ("action", "admin_counsellors_link", "Assign a counsellor"),
             ("small", "Assign a counsellor on the Counsellor &harr; Assessment page to let the student book.")],
     changes=["Counselling house style becomes the shell with an Internal tag; \"Dear Admin,\" goes."]),

# ── Other ──────────────────────────────────────────────────────────────────────
dict(id="lead-welcome", status="rewritten",
     subject="Thanks for getting in touch with Career-9",
     pre="We have your enquiry and will be in touch shortly.",
     blocks=[("title", "Thanks for getting in touch"), HI,
             ("p", "We have your enquiry and someone from our team will contact you shortly."),
             ("p", "<b>Here is what you sent us:</b>"),
             ("details", [("Name", "{{lead_name}}"), ("Email", "{{lead_email}}"), ("Phone", "{{lead_phone}}"), ("Enquiry type", "{{lead_type}}"), ("School", "{{lead_school}}"), ("City", "{{lead_city}}")]),
             ("action", "site_link", "Explore Career-9"), SIG],
     changes=["C9 badge header and bare div become the shell.",
              "\"Warm regards, Team Career-9\" becomes the standard sign-off; a button to the website is added.",
              "Seeded admin template migrated if unchanged."]),

# ── Counselling ────────────────────────────────────────────────────────────────
dict(id="counselling-booking-confirmation", status="restyled",
     subject="Your counselling session is booked",
     pre="{{session_date}}, {{session_time}} with {{counsellor_name}}. Join link inside.",
     blocks=[("title", "It&rsquo;s official &#127881; Your counselling session is booked"),
             ("p", "Hi {{first_name}} &#128075;"),
             ("p", "You&rsquo;ve taken an important step towards understanding your strengths, exploring possibilities, and getting clarity about your future. &#128640;"),
             ("details", [("Student", "{{student_name}}"), ("School", "{{institute_name}}"), ("Assessment", "{{assessment_name}}")] + SESSION_ROWS),
             ("action", "join_link", "Join the session"),
             ("outline", "calendar_link", "Add to Google Calendar"),
             ("small", "A calendar invite is also attached so you can add this to any calendar."),
             ("p", "<b>&#128161; Come curious. Leave clear.</b> This is your session, so bring all your questions:"),
             ("list", ["&#129300; &ldquo;Which career is right for me?&rdquo;", "&#127919; &ldquo;What am I really good at?&rdquo;",
                       "&#128218; &ldquo;Which subjects should I choose?&rdquo;", "&#128640; &ldquo;What options do I have after school or college?&rdquo;"]),
             ("p", "Ask. Explore. Challenge. Discover. Your Career-9 report has the insights. Now, let&rsquo;s turn those insights into possibilities. &#128153;"),
             ("small", "Need to make a change? Write to support@career-9.net before the session so we can put it right."), SIG],
     changes=["Green campaign design becomes the shell; every emoji stays; the .ics attachment is unchanged.",
              "The meeting URL printed as text becomes the short-link line under the button.",
              "\"Team Career-9\" becomes the standard sign-off; \"write to us\" names the support address."]),
dict(id="counselling-request-received", status="deleted", changes=["Defined but never called (bookings are auto-confirmed). Deleted."]),
dict(id="counselling-assigned-to-counsellor", status="rewritten",
     subject="New counselling session assigned to you",
     pre="{{student_name}}, {{session_date}} at {{session_time}}. Please review and confirm.",
     blocks=[("title", "New session assigned to you"), HI_C,
             ("p", "A new counselling session has been assigned to you."),
             ("details", [("Reason", "{{student_reason}}"), ("Student", "{{student_name}}"), ("School", "{{institute_name}}"), ("Assessment", "{{assessment_name}}"),
                          ("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Mode", "{{session_mode}}")]),
             ("action", "counsellor_portal_link", "Review and confirm"),
             ("linkline", [("report_link", "Open the assessment report")]),
             ("small", "Once you confirm, the student receives the meeting details."), SIG],
     changes=["Counselling house style becomes the shell.",
              "The primary button now goes to the portal to confirm (the mail asks for a confirmation); the join link arrives in the confirmed mail. The report becomes a labelled link.",
              "Raw meeting URL removed."]),
dict(id="counselling-confirmed-to-student", status="restyled",
     subject="Your counselling session is confirmed",
     pre="{{session_date}} at {{session_time}}. Join link inside.",
     blocks=[("title", "Your counselling session is confirmed"), HI,
             ("p", "Your counselling session has been confirmed."),
             ("details", [("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Duration", "{{duration}} minutes"), ("Mode", "{{session_mode}}")]),
             ("action", "join_link", "Join the session"), EARLY, SIG],
     changes=["Counselling house style becomes the shell; raw meeting URL becomes the short-link line."]),
dict(id="counselling-cancelled-notice", status="restyled",
     subject="Counselling session cancelled",
     pre="{{session_date}}, {{session_time}}: cancelled by {{cancelled_by}}.",
     blocks=[("title", "Counselling session cancelled"), HI,
             ("p", "Your counselling session on <b>{{session_date}}</b> at <b>{{session_time}}</b> has been cancelled by <b>{{cancelled_by}}</b>."),
             ("notice", "Reason given: {{reason}}"),
             ("action", "sessions_link", "View my sessions"),
             ("small", "If you have any questions, write to support@career-9.net."), SIG],
     changes=["Counselling house style becomes the shell. The greeting and button label follow the recipient (student or counsellor).",
              "\"Please contact us\" names the support address."]),
dict(id="counselling-student-cancellation-confirmation", status="restyled",
     subject="Your counselling session has been cancelled",
     pre="Cancelled as you asked. You have {{changes_left}} free change left.",
     blocks=[("title", "Your session has been cancelled"), HI,
             ("p", "Your counselling session on <b>{{session_date}}</b> at <b>{{session_time}}</b> has been cancelled as you requested."),
             ("notice", "Your session has been returned to your plan, so you can book again. You have <b>{{changes_left}}</b> free change left."),
             ("p", "Ready to pick a new time?"),
             ("action", "sessions_link", "Book a new time"), SIG],
     changes=["Counselling house style becomes the shell; the cancel .ics is unchanged.",
              "Bug fix: when the .ics is attached the mail currently has no plain-text part; the theme always produces one."]),
dict(id="counselling-admin-cancellation", status="restyled",
     subject="Your counselling session has been cancelled",
     pre="Cancelled by the Career-9 team. Your entitlement is unaffected.",
     blocks=[("title", "Your session has been cancelled"), HI,
             ("p", "Your counselling session on <b>{{session_date}}</b> at <b>{{session_time}}</b> has been cancelled by the Career-9 team."),
             ("notice", "This does not affect your counselling entitlement. Our team will be in touch shortly to arrange a new time."),
             ("p", "Prefer not to wait?"),
             ("action", "sessions_link", "Pick a new time"),
             ("small", "We apologise for the inconvenience."), SIG],
     changes=["Counselling house style becomes the shell. The counsellor copy keeps its own title (\"A counselling session has been cancelled\") and a dashboard button."]),
dict(id="counselling-counsellor-leave-cancellation", status="deleted", changes=["Defined but never called (the block-date flow sends the self-reschedule mail). Deleted."]),
dict(id="counselling-self-reschedule", status="restyled",
     subject="Please pick a new time for your counselling session",
     pre="Your session has not been cancelled. Choose a new slot, no login needed.",
     blocks=[("title", "Pick a new time for your session"), HI,
             ("p", "{{opening}}"),
             ("notice", "Reason: {{reason}}"),
             ("p", "Your session has <b>not</b> been cancelled. Please pick a new slot that suits you; no login is needed."),
             ("action", "reschedule_link", "Pick a new slot"),
             ("small", "Once you choose a time, your session is confirmed instantly and you will get the meeting details by email. We are sorry for the inconvenience."), SIG],
     changes=["Counselling house style becomes the shell; the tokenised reschedule URL under the button becomes the short link.",
              "The reason panel appears only when an admin gave one (unchanged)."]),
dict(id="counselling-rescheduled", status="restyled",
     subject="Your counselling session has been rescheduled",
     pre="Now {{new_session_date}} at {{new_session_time}}. Updated join link inside.",
     blocks=[("title", "Your session has been rescheduled"), HI,
             ("p", "Your counselling session has moved. Here is the new schedule."),
             ("details", [("Previously", "{{old_session_date}}, {{old_session_time}}"), ("New date", "{{new_session_date}}"), ("New time", "{{new_session_time}}"),
                          ("Counsellor", "{{counsellor_name}}"), ("Mode", "{{session_mode}}")]),
             ("action", "join_link", "Join the session"),
             ("small", "Please update your calendar and join a few minutes before the start time."), SIG],
     changes=["Two stacked tables (previous and new) become one details panel with a \"Previously\" row.",
              "Counsellor copy keeps the student row and the report link."]),
dict(id="counselling-reminder-fallback", status="restyled",
     subject="Your counselling session is {{when_label}}",
     pre="{{session_date}}, {{session_time}}. Join link inside.",
     blocks=[("title", "Your counselling session is {{when_label}}"), HI,
             ("p", "This is a reminder that your counselling session is <b>{{when_label}}</b>."),
             ("details", SESSION_ROWS),
             ("action", "join_link", "Join the session"),
             ("linkline", [("report_link", "Open your assessment report")]),
             EARLY, SIG],
     changes=["Counselling house style becomes the shell.",
              "Bug fix: the scheduler passes \"in 12 hours\" and the mail prepends another \"in\", producing \"in in 12 hours\". The label is used once."]),
dict(id="counselling-counsellor-reminder-fallback", status="restyled",
     subject="Reminder: session {{when_label}} with {{student_name}}",
     pre="{{session_date}}, {{session_time}}. Join link inside.",
     blocks=[("title", "Session {{when_label}}: {{student_name}}"), HI_C,
             ("p", "You have a counselling session <b>{{when_label}}</b> with <b>{{student_name}}</b>."),
             ("details", [("Student", "{{student_name}}"), ("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Mode", "{{session_mode}}")]),
             ("action", "join_link", "Join the session"), EARLY, SIG],
     changes=["Counselling house style becomes the shell; raw meeting URL becomes the short-link line."]),
dict(id="counselling-session-complete-thankyou", status="restyled",
     subject="Thank you for your session with Career-9",
     pre="We hope it brought clarity. Know someone who needs it too?",
     blocks=[("title", "Thank you for being a part of Career-9 &#127775;"),
             ("p", "Hi {{first_name}} &#128075;"),
             ("p", "We hope your counselling session helped you discover new possibilities, understand yourself better, and take a step closer to making confident career choices. &#128640;"),
             ("p", "Remember, your career journey doesn&rsquo;t end with one session. Keep exploring, keep learning, and keep believing in yourself."),
             ("p", "<b>&#128153; Know someone who needs career clarity?</b> If you found your Career-9 experience valuable, share it with friends, cousins or family members who may also be wondering &ldquo;What should I choose for my future?&rdquo; &#129300;"),
             ("action", "referral_link", "Refer a friend or family member"),
             ("p", "<b>&#128260; See you again in 6 months.</b> Your interests, strengths and aspirations evolve as you grow, so we would love to reconnect in 6 months and see what has changed and where you want to go next."),
             ("p", "Your future is a journey. We&rsquo;re happy to be part of it. &#128153;"), SIG],
     changes=["Green campaign design becomes the shell; every emoji stays.",
              "\"Warm regards, Team Career-9\" becomes the standard sign-off."]),
dict(id="counselling-session-summary-student", status="restyled",
     subject="Your counselling session details",
     pre="{{session_date}}, {{session_time}} with {{counsellor_name}}. Join link and report inside.",
     blocks=[("title", "Your counselling session"), HI,
             ("p", "Here are the details of your counselling session with <b>{{counsellor_name}}</b>."),
             ("details", [("School", "{{institute_name}}"), ("Assessment", "{{assessment_name}}")] + SESSION_ROWS),
             ("action", "join_link", "Join the session"),
             ("linkline", [("report_link", "Open your assessment report")]),
             ("small", "{{report_guidance}}"),
             ("small", "If any of the above is incorrect, write to support@career-9.net before the session so we can put it right."), SIG],
     changes=["Counselling house style becomes the shell; raw meeting URL becomes the short-link line; \"write to us\" names the address."]),
dict(id="counselling-session-summary-counsellor", status="restyled",
     subject="Counselling session: {{student_name}}",
     pre="{{session_date}}, {{session_time}}. Join link and report inside.",
     blocks=[("title", "Counselling session: {{student_name}}"), HI_C,
             ("p", "Here are the details of your counselling session with <b>{{student_name}}</b>."),
             ("details", [("Student", "{{student_name}}"), ("School", "{{institute_name}}"), ("Assessment", "{{assessment_name}}"),
                          ("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Mode", "{{session_mode}}")]),
             ("action", "join_link", "Join the session"),
             ("linkline", [("report_link", "Open the assessment report")]),
             ("small", "Please read the report before the session."), SIG],
     changes=["Counselling house style becomes the shell; raw meeting URL becomes the short-link line."]),
dict(id="counselling-booking-invite", status="restyled",
     subject="Book your counselling session",
     pre="Pick a time that suits you. No login needed.",
     blocks=[("title", "Book your counselling session"), HI,
             ("p", "You have completed your assessment. The next step is a one-to-one counselling session to turn your results into a real plan."),
             ("action", "booking_link", "Book my session"),
             ("small", "No login needed. Once you choose a slot, your session is confirmed instantly and you will receive the meeting details by email."), SIG],
     changes=["Counselling house style becomes the shell; the tokenised booking URL becomes the short link."]),
dict(id="counselling-daily-digest", status="restyled",
     subject="Your sessions for {{digest_date}} ({{session_count}})",
     pre="{{session_count}} sessions tomorrow. Times and students inside.",
     blocks=[("title", "Your sessions for {{digest_date}}"), HI_C,
             ("p", "Here are your counselling sessions scheduled for <b>{{digest_date}}</b>:"),
             ("table", ["Time", "Student", "Mode"], [["10:00 &ndash; 10:30 AM", "Aarav Sharma", "Online"], ["11:30 AM &ndash; 12:00 PM", "Diya Patel", "Online"], ["3:00 &ndash; 3:30 PM", "Kabir Rao", "In-person"]]),
             ("action", "counsellor_portal_link", "Open my dashboard"),
             ("small", "Please be available on time."), SIG],
     changes=["Counselling house style becomes the shell; the session list becomes a table; raw dashboard URL removed."]),
dict(id="counselling-booking-nudge-fallback", status="restyled",
     subject="A counselling session is waiting for you",
     pre="{{sessions_left}} session in your plan hasn't been booked yet. Pick a time.",
     blocks=[("title", "A counselling session is waiting for you"), HI,
             ("p", "You have <b>{{sessions_left}}</b> counselling session included in your plan that hasn&rsquo;t been booked yet."),
             ("action", "sessions_link", "Book my session"),
             ("small", "Sign in and pick a time that works for you to speak with a counsellor."), SIG],
     changes=["Counselling house style becomes the shell; raw dashboard URL removed.",
              "Behaviour note: the same run also sends the B2C booking link; the rewrite sends one mail."]),
dict(id="counselling-no-show-student", status="deleted", changes=["Defined but never called (absence is handled by the marked-absent mail). Deleted."]),
dict(id="counselling-counsellor-swapped", status="restyled",
     subject="Your session is confirmed with updated details",
     pre="Same time, different counsellor. Use the updated join link.",
     blocks=[("title", "Your session is confirmed, with updated details"), HI,
             ("p", "Your counselling session on <b>{{session_date}}</b> at <b>{{session_time}}</b> is going ahead exactly as planned. The time has not changed."),
             ("p", "A different counsellor, <b>{{new_counsellor_name}}</b>, will now be taking it, so please use the updated joining link below."),
             ("action", "join_link", "Join the session"), EARLY, SIG],
     changes=["Counselling house style becomes the shell; the new counsellor is named; raw meeting URL becomes the short-link line."]),
dict(id="counselling-session-shifted", status="restyled",
     subject="Your counselling session has moved to {{new_session_time}}",
     pre="Moved from {{old_session_time}} to {{new_session_time}} on {{session_date}}.",
     blocks=[("title", "Your counselling session has moved"), HI,
             ("p", "Your counsellor is no longer available at <b>{{old_session_time}}</b>, so we have moved your session to <b>{{new_session_time}}</b> on <b>{{session_date}}</b>."),
             ("action", "join_link", "Join the session"),
             ("p", "If the new time does not suit you, you can pick another one. Choosing your own time uses one of your free changes."),
             ("outline", "reschedule_link", "Choose another time"),
             ("small", "We are sorry for the disruption."), SIG],
     changes=["Counselling house style becomes the shell; two action panels become a primary and an outline button; both raw URLs go."]),
dict(id="counselling-checkin-code", status="restyled",
     subject="Your counselling check-in code",
     pre="Read this code out to your counsellor to start the session.",
     blocks=[("title", "Your check-in code"), HI,
             ("p", "Read the code below out to your counsellor to start your counselling session."),
             ("code", "{{checkin_code}}", "Check-in code"),
             ("details", [("Date", "{{session_date}}"), ("Time", "{{session_time}}"), ("Counsellor", "{{counsellor_name}}")]),
             ("action", "join_link", "Join the session"),
             ("small", "This is the same 4-digit code printed on your Career-9 report. Please don&rsquo;t share it with anyone else; it is what records you as present."), SIG],
     changes=["Counselling house style becomes the shell; the code stays the largest thing on the page; details trimmed to date, time and counsellor."]),
dict(id="counselling-checkin-prompt-student", status="restyled",
     subject="Your counselling session is waiting to start",
     pre="Read out your check-in code so the session can begin.",
     blocks=[("title", "Your session is waiting to start"), HI,
             ("p", "Your session has not been started yet. Please read out the 4-digit check-in code from your Career-9 report so your counsellor can begin."),
             ("action", "join_link", "Join the session"),
             ("linkline", [("sessions_link", "Find my check-in code")]),
             ("small", "If nobody has joined, you do not need to do anything else. Your session will be preserved and we will send you a link to pick a new time."), SIG],
     changes=["Counselling house style becomes the shell; raw meeting URL becomes the short-link line."]),
dict(id="counselling-checkin-prompt-counsellor", status="restyled",
     subject="Action needed: session with {{student_name}} not started",
     pre="The {{session_time}} session has not been checked in.",
     blocks=[("title", "Action needed: session not started"), HI_C,
             ("p", "Your <b>{{session_time}}</b> session with <b>{{student_name}}</b> has not been checked in."),
             ("p", "Please either enter the student&rsquo;s check-in code, or mark the student absent if they have not appeared."),
             ("action", "counsellor_portal_link", "Open the session"),
             ("notice", "If neither is recorded before the session ends, it will be logged as your no-show rather than the student&rsquo;s."), SIG],
     changes=["Counselling house style becomes the shell; the warning becomes a notice panel; raw dashboard URL removed."]),
dict(id="counselling-marked-absent", status="restyled",
     subject="You were marked absent from your counselling session",
     pre="Here is where you stand and what you can do next.",
     blocks=[("title", "You were marked absent"), HI,
             ("p", "Your counsellor has recorded that you did not attend your session on <b>{{session_date}}</b> at <b>{{session_time}}</b>."),
             ("notice", "You have <b>{{changes_left}}</b> free change left."),
             ("p", "{{next_step_lead}}"),
             ("action", "sessions_link", "Book a new time"),
             ("small", "If you were present and believe this is a mistake, raise it from your Career-9 dashboard or write to support@career-9.net. The session will be reviewed and nothing counts against you until it is settled."), SIG],
     changes=["Counselling house style becomes the shell.",
              "\"Reply to this email\" becomes \"write to support@career-9.net\" (the sending address is not a read inbox)."]),
dict(id="counselling-dispute-outcome", status="restyled",
     subject="Your counselling session has been corrected",
     pre="Your session on {{session_date}} is now recorded as attended.",
     blocks=[("title", "Your session has been corrected"), HI,
             ("p", "We have reviewed your session on <b>{{session_date}}</b> and corrected it. It is now recorded as attended, and nothing has been counted against you."),
             ("notice", "Note from our team: {{dispute_note}}"),
             ("action", "sessions_link", "View my sessions"), SIG],
     changes=["Counselling house style becomes the shell; \"Good news —\" dropped from the subject.",
              "Upheld variant keeps its own subject (\"Your attendance review outcome\") and wording."]),
dict(id="counsellor-deactivated-notice", status="restyled", cta_optional=True,
     subject="Your Career-9 counsellor account has been deactivated",
     pre="You can no longer sign in to the counsellor portal.",
     blocks=[("title", "Your counsellor account has been deactivated"), HI_C,
             ("p", "Your Career-9 counsellor account has been deactivated by the team. You will not be able to sign in to the counsellor portal, and no new sessions can be booked with you."),
             ("p", "{{sessions_sentence}}"),
             ("small", "If you believe this is a mistake, write to support@career-9.net."), SIG],
     changes=["Counselling house style becomes the shell; \"contact the Career-9 team\" names the address. No button: there is nothing to open."]),
dict(id="counsellor-deactivated-student", status="restyled",
     subject="Your counselling session has been cancelled",
     pre="Your counsellor is no longer available. Choose a new time right away, no login needed.",
     blocks=[("title", "Your session has been cancelled"), HI,
             ("p", "Your counselling session on <b>{{session_date}}</b> at <b>{{session_time}}</b> has been cancelled by the Career-9 team, as your counsellor is no longer available."),
             ("notice", "This does not affect your counselling entitlement. Another counsellor is available, so you can choose a new time right away."),
             ("action", "reschedule_link", "Pick a new slot"),
             ("small", "No login is needed; the link opens your booking page directly. If you would rather we arranged it for you, write to support@career-9.net. We apologise for the inconvenience."), SIG],
     changes=["Counselling house style becomes the shell; the cancel .ics is unchanged.",
              "\"Simply reply to this email\" becomes \"write to support@career-9.net\"."]),
]

BY_ID = {s["id"]: s for s in SPECS}
