FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends mysql-client cron bash && \
    rm -rf /var/lib/apt/lists/*

COPY sync-master-to-staging.sh /usr/local/bin/sync-master-to-staging.sh
RUN chmod +x /usr/local/bin/sync-master-to-staging.sh

COPY crontab /etc/crontabs/root
RUN crontab /etc/crontabs/root

CMD ["cron", "-f"]
