-- ---------------------------------------------------------------------------
-- V20260512001__seed_phase15_permissions.sql
--
-- Phase 15 PREFLIGHT — extends Phase 14's permission catalog with all
-- codes required by plans 15-03 (Student & Counselling slice), 15-04
-- (Assessment / Questionnaire / Scoring / Report slice), and 15-05
-- (Institute / Admin / Payments / B2C / Dashboard slice).
--
-- This migration is the cross-cutting unblock step identified in
-- 15-03-SUMMARY.md, 15-04-SUMMARY.md, and 15-05-SUMMARY.md as the
-- prerequisite for re-running Wave 2 controller-annotation plans.
--
-- Idempotent: re-running on a partially-seeded DB updates descriptions on
-- existing codes (via ON DUPLICATE KEY UPDATE) and inserts the missing ones.
-- Same pattern as V20260511002__seed_permissions.sql.
--
-- Row count: 411 (matches PermissionCode.values().length after this extension).
-- The 28 codes seeded by V20260511002 are included here for completeness and
-- will silently UPDATE; the ~383 new codes will INSERT.
-- ---------------------------------------------------------------------------

INSERT INTO permission (code, description) VALUES
  ('institute.read', 'View institute details'),
  ('institute.write', 'Create or update institutes'),
  ('institute.delete', 'Delete institutes'),
  ('session.read', 'View academic sessions'),
  ('session.write', 'Create or update sessions'),
  ('class.read', 'View classes / courses'),
  ('class.write', 'Create or update classes / courses'),
  ('section.read', 'View sections'),
  ('section.write', 'Create or update sections'),
  ('student.read', 'View students'),
  ('student.write', 'Create or update students'),
  ('student.import_bulk', 'Bulk-import students from CSV/Excel'),
  ('assessment.read', 'View assessments'),
  ('assessment.create', 'Create assessments'),
  ('assessment.publish', 'Publish assessments to students'),
  ('assessment.delete', 'Delete assessments'),
  ('campaign.read', 'View marketing/payment campaigns'),
  ('campaign.write', 'Create or update campaigns'),
  ('campaign.publish', 'Publish/activate campaigns'),
  ('report.read', 'View generated reports'),
  ('report.export', 'Export reports (PDF/Excel)'),
  ('user.read', 'View user accounts'),
  ('user.write', 'Create or update user accounts'),
  ('user.toggle_active', 'Activate or deactivate users'),
  ('payment.refund', 'Issue payment refunds'),
  ('payment.webhook.handle', 'Handle Razorpay webhook (system role)'),
  ('role.assign', 'Assign roles to users'),
  ('permission.grant', 'Grant/revoke individual permissions'),
  ('assessment.read.all', 'View assessments across all scopes'),
  ('assessment.update', 'Update assessment definitions'),
  ('assessment.start', 'Start an assessment session'),
  ('assessment.submit', 'Submit an assessment session'),
  ('assessment.prefetch', 'Prefetch assessment payload for student app'),
  ('student.create', 'Create individual students'),
  ('student.update', 'Update individual students'),
  ('student.delete', 'Delete individual students'),
  ('student.read.all', 'View students across all scopes'),
  ('student.import', 'Import students (single-row CSV/Excel)'),
  ('student.export', 'Export student lists (CSV/Excel/PDF)'),
  ('user.me', 'View own user profile'),
  ('user.read.all', 'View user accounts across all scopes'),
  ('user.create', 'Create user accounts'),
  ('user.update', 'Update user accounts'),
  ('user.delete', 'Delete user accounts'),
  ('role.read', 'View roles'),
  ('role.read.all', 'View all roles across scopes'),
  ('role.create', 'Create roles'),
  ('role.update', 'Update roles'),
  ('role.delete', 'Delete roles'),
  ('role_group.read', 'View role groups'),
  ('role_group.read.all', 'View all role groups across scopes'),
  ('role_group.create', 'Create role groups'),
  ('role_group.update', 'Update role groups'),
  ('role_group.delete', 'Delete role groups'),
  ('role_role_group_mapping.read', 'View role-to-role-group mappings'),
  ('role_role_group_mapping.read.all', 'View all role-to-role-group mappings across scopes'),
  ('role_role_group_mapping.create', 'Create role-to-role-group mappings'),
  ('role_role_group_mapping.update', 'Update role-to-role-group mappings'),
  ('role_role_group_mapping.delete', 'Delete role-to-role-group mappings'),
  ('user_role_group_mapping.read', 'View user-to-role-group mappings'),
  ('user_role_group_mapping.read.all', 'View all user-to-role-group mappings across scopes'),
  ('user_role_group_mapping.create', 'Create user-to-role-group mappings'),
  ('user_role_group_mapping.update', 'Update user-to-role-group mappings'),
  ('user_role_group_mapping.delete', 'Delete user-to-role-group mappings'),
  ('group.read', 'View groups'),
  ('group.read.all', 'View all groups across scopes'),
  ('group.create', 'Create groups'),
  ('group.update', 'Update groups'),
  ('group.delete', 'Delete groups'),
  ('google_admin.read', 'View Google Workspace admin data'),
  ('google_admin.create', 'Create Google Workspace admin entities'),
  ('google_admin.update', 'Update Google Workspace admin entities'),
  ('google_admin.delete', 'Delete Google Workspace admin entities'),
  ('google_groups.read', 'View Google Workspace groups'),
  ('google_groups.create', 'Create Google Workspace groups'),
  ('google_groups.update', 'Update Google Workspace groups'),
  ('google_groups.delete', 'Delete Google Workspace groups'),
  ('data.read', 'View bulk data dumps'),
  ('list.read', 'View list endpoints'),
  ('util.read', 'View utility endpoint output'),
  ('util.execute', 'Execute utility operations'),
  ('institute_batch.read', 'View institute batches'),
  ('institute_batch.read.all', 'View all institute batches across scopes'),
  ('institute_batch.create', 'Create institute batches'),
  ('institute_batch.update', 'Update institute batches'),
  ('institute_batch.delete', 'Delete institute batches'),
  ('institute_branch.read', 'View institute branches'),
  ('institute_branch.read.all', 'View all institute branches across scopes'),
  ('institute_branch.create', 'Create institute branches'),
  ('institute_branch.update', 'Update institute branches'),
  ('institute_branch.delete', 'Delete institute branches'),
  ('institute_branch_batch_mapping.read', 'View institute branch-batch mappings'),
  ('institute_branch_batch_mapping.read.all', 'View all institute branch-batch mappings across scopes'),
  ('institute_branch_batch_mapping.create', 'Create institute branch-batch mappings'),
  ('institute_branch_batch_mapping.update', 'Update institute branch-batch mappings'),
  ('institute_branch_batch_mapping.delete', 'Delete institute branch-batch mappings'),
  ('institute_course.read', 'View institute courses'),
  ('institute_course.read.all', 'View all institute courses across scopes'),
  ('institute_course.create', 'Create institute courses'),
  ('institute_course.update', 'Update institute courses'),
  ('institute_course.delete', 'Delete institute courses'),
  ('institute_session.read', 'View institute sessions'),
  ('institute_session.read.all', 'View all institute sessions across scopes'),
  ('institute_session.create', 'Create institute sessions'),
  ('institute_session.update', 'Update institute sessions'),
  ('institute_session.delete', 'Delete institute sessions'),
  ('institute_detail.read', 'View institute detail records'),
  ('institute_detail.read.all', 'View all institute detail records across scopes'),
  ('institute_detail.create', 'Create institute detail records'),
  ('institute_detail.update', 'Update institute detail records'),
  ('institute_detail.delete', 'Delete institute detail records'),
  ('report_generation.read', 'View report-generation jobs'),
  ('report_generation.read.all', 'View all report-generation jobs across scopes'),
  ('report_generation.create', 'Create report-generation jobs'),
  ('report_generation.update', 'Update report-generation jobs'),
  ('report_generation.delete', 'Delete report-generation jobs'),
  ('school_session.read', 'View school sessions'),
  ('school_session.read.all', 'View all school sessions across scopes'),
  ('school_session.create', 'Create school sessions'),
  ('school_session.update', 'Update school sessions'),
  ('school_session.delete', 'Delete school sessions'),
  ('dashboard.admin', 'Access admin dashboard'),
  ('dashboard.admin.read', 'Read admin dashboard data'),
  ('dashboard.principal', 'Access principal dashboard'),
  ('dashboard.principal.read', 'Read principal dashboard data'),
  ('dashboard.teacher', 'Access teacher dashboard'),
  ('dashboard.teacher.read', 'Read teacher dashboard data'),
  ('payment.create', 'Create payments'),
  ('payment.verify', 'Verify payments'),
  ('payment.read', 'View payments'),
  ('payment.read.all', 'View all payments across scopes'),
  ('payment_webhook.read', 'View payment webhook records'),
  ('payment_webhook.list', 'List payment webhook records'),
  ('promo_code.read', 'View promo codes'),
  ('promo_code.read.all', 'View all promo codes across scopes'),
  ('promo_code.create', 'Create promo codes'),
  ('promo_code.update', 'Update promo codes'),
  ('promo_code.delete', 'Delete promo codes'),
  ('campaign.public', 'Access public-facing campaign endpoints'),
  ('campaign.create', 'Create campaigns'),
  ('campaign.update', 'Update campaigns'),
  ('campaign.delete', 'Delete campaigns'),
  ('campaign.read.all', 'View all campaigns across scopes'),
  ('entitlement.read', 'View entitlements'),
  ('entitlement.read.all', 'View all entitlements across scopes'),
  ('entitlement.create', 'Create entitlements'),
  ('entitlement.update', 'Update entitlements'),
  ('entitlement.delete', 'Delete entitlements'),
  ('pricing_tier.read', 'View pricing tiers'),
  ('pricing_tier.read.all', 'View all pricing tiers across scopes'),
  ('pricing_tier.create', 'Create pricing tiers'),
  ('pricing_tier.update', 'Update pricing tiers'),
  ('pricing_tier.delete', 'Delete pricing tiers'),
  ('report_preparation.read', 'View report-preparation records'),
  ('report_preparation.create', 'Create report-preparation records'),
  ('report_preparation.update', 'Update report-preparation records'),
  ('report_preparation.delete', 'Delete report-preparation records'),
  ('tracker.read', 'View trackers'),
  ('tracker.read.all', 'View all trackers across scopes'),
  ('tracker.create', 'Create trackers'),
  ('tracker.update', 'Update trackers'),
  ('tracker.delete', 'Delete trackers'),
  ('assessment_answer.read', 'View assessment answers'),
  ('assessment_answer.read.all', 'View all assessment answers across scopes'),
  ('assessment_answer.create', 'Create assessment answers'),
  ('assessment_answer.update', 'Update assessment answers'),
  ('assessment_answer.delete', 'Delete assessment answers'),
  ('assessment_answer.submit', 'Submit assessment answers'),
  ('assessment_demographic_mapping.read', 'View assessment-demographic mappings'),
  ('assessment_demographic_mapping.create', 'Create assessment-demographic mappings'),
  ('assessment_demographic_mapping.update', 'Update assessment-demographic mappings'),
  ('assessment_demographic_mapping.delete', 'Delete assessment-demographic mappings'),
  ('assessment_institute_mapping.read', 'View assessment-institute mappings'),
  ('assessment_institute_mapping.create', 'Create assessment-institute mappings'),
  ('assessment_institute_mapping.update', 'Update assessment-institute mappings'),
  ('assessment_institute_mapping.delete', 'Delete assessment-institute mappings'),
  ('assessment_proctoring.read', 'View assessment proctoring data'),
  ('assessment_proctoring.create', 'Create assessment proctoring records'),
  ('assessment_proctoring.update', 'Update assessment proctoring records'),
  ('assessment_proctoring.delete', 'Delete assessment proctoring records'),
  ('assessment_question.read', 'View assessment questions'),
  ('assessment_question.read.all', 'View all assessment questions across scopes'),
  ('assessment_question.create', 'Create assessment questions'),
  ('assessment_question.update', 'Update assessment questions'),
  ('assessment_question.delete', 'Delete assessment questions'),
  ('assessment_question.import', 'Import assessment questions from Excel'),
  ('assessment_question.export', 'Export assessment questions to Excel'),
  ('assessment_question_option.read', 'View assessment-question options'),
  ('assessment_question_option.create', 'Create assessment-question options'),
  ('assessment_question_option.update', 'Update assessment-question options'),
  ('assessment_question_option.delete', 'Delete assessment-question options'),
  ('bet_report_data.read', 'View BET report data'),
  ('bet_report_data.read.all', 'View all BET report data across scopes'),
  ('bet_report_data.create', 'Create BET report data'),
  ('bet_report_data.update', 'Update BET report data'),
  ('bet_report_data.delete', 'Delete BET report data'),
  ('dashboard_snapshot.read', 'View dashboard snapshots'),
  ('dashboard_snapshot.create', 'Create dashboard snapshots'),
  ('dashboard_snapshot.update', 'Update dashboard snapshots'),
  ('four_pager_template.read', 'View 4-pager report templates'),
  ('four_pager_template.update', 'Update 4-pager report templates'),
  ('game_results.read', 'View game results'),
  ('game_results.create', 'Create game results'),
  ('game_results.update', 'Update game results'),
  ('game_results.delete', 'Delete game results'),
  ('game_table.read', 'View game-table definitions'),
  ('game_table.create', 'Create game-table definitions'),
  ('game_table.update', 'Update game-table definitions'),
  ('game_table.delete', 'Delete game-table definitions'),
  ('general_assessment.read', 'View general assessments'),
  ('general_assessment.create', 'Create general assessments'),
  ('general_assessment.update', 'Update general assessments'),
  ('general_assessment.delete', 'Delete general assessments'),
  ('generated_report.read', 'View generated reports'),
  ('generated_report.read.all', 'View all generated reports across scopes'),
  ('generated_report.create', 'Create generated reports'),
  ('generated_report.update', 'Update generated reports'),
  ('generated_report.delete', 'Delete generated reports'),
  ('navigator_report_data.read', 'View Navigator report data'),
  ('navigator_report_data.read.all', 'View all Navigator report data across scopes'),
  ('navigator_report_data.create', 'Create Navigator report data'),
  ('navigator_report_data.update', 'Update Navigator report data'),
  ('navigator_report_data.delete', 'Delete Navigator report data'),
  ('language_option.read', 'View language options'),
  ('language_option.create', 'Create language options'),
  ('language_option.update', 'Update language options'),
  ('language_option.delete', 'Delete language options'),
  ('language_question.read', 'View language questions'),
  ('language_question.create', 'Create language questions'),
  ('language_question.update', 'Update language questions'),
  ('language_question.delete', 'Delete language questions'),
  ('language_supported.read', 'View supported languages'),
  ('language_supported.create', 'Create supported languages'),
  ('language_supported.update', 'Update supported languages'),
  ('language_supported.delete', 'Delete supported languages'),
  ('measured_quality.read', 'View measured qualities'),
  ('measured_quality.create', 'Create measured qualities'),
  ('measured_quality.update', 'Update measured qualities'),
  ('measured_quality.delete', 'Delete measured qualities'),
  ('measured_quality_type.read', 'View measured-quality types'),
  ('measured_quality_type.create', 'Create measured-quality types'),
  ('measured_quality_type.update', 'Update measured-quality types'),
  ('measured_quality_type.delete', 'Delete measured-quality types'),
  ('omr_column_mapping.read', 'View OMR column mappings'),
  ('omr_column_mapping.create', 'Create OMR column mappings'),
  ('omr_column_mapping.update', 'Update OMR column mappings'),
  ('omr_column_mapping.delete', 'Delete OMR column mappings'),
  ('option_score.read', 'View option scores'),
  ('option_score.create', 'Create option scores'),
  ('option_score.update', 'Update option scores'),
  ('option_score.delete', 'Delete option scores'),
  ('question_media.read', 'View question media'),
  ('question_media.create', 'Create question media'),
  ('question_media.delete', 'Delete question media'),
  ('question_section.read', 'View question sections'),
  ('question_section.create', 'Create question sections'),
  ('question_section.update', 'Update question sections'),
  ('question_section.delete', 'Delete question sections'),
  ('questionnaire.read', 'View questionnaires'),
  ('questionnaire.read.all', 'View all questionnaires across scopes'),
  ('questionnaire.create', 'Create questionnaires'),
  ('questionnaire.update', 'Update questionnaires'),
  ('questionnaire.delete', 'Delete questionnaires'),
  ('questionnaire_language.read', 'View questionnaire languages'),
  ('questionnaire_language.create', 'Create questionnaire languages'),
  ('questionnaire_language.update', 'Update questionnaire languages'),
  ('questionnaire_language.delete', 'Delete questionnaire languages'),
  ('report_template.read', 'View report templates'),
  ('report_template.create', 'Create report templates'),
  ('report_template.update', 'Update report templates'),
  ('report_template.delete', 'Delete report templates'),
  ('report_zip.read', 'View report ZIP bundles'),
  ('report_zip.create', 'Create report ZIP bundles'),
  ('report_zip.update', 'Update report ZIP bundles'),
  ('tool.read', 'View psychometric tools'),
  ('tool.create', 'Create psychometric tools'),
  ('tool.update', 'Update psychometric tools'),
  ('tool.delete', 'Delete psychometric tools'),
  ('student_info.read', 'View student info records'),
  ('student_info.read.all', 'View all student info records across scopes'),
  ('student_info.create', 'Create student info records'),
  ('student_info.update', 'Update student info records'),
  ('student_info.delete', 'Delete student info records'),
  ('student_info.import', 'Import student info records'),
  ('temporary_student.read', 'View temporary students'),
  ('temporary_student.create', 'Create temporary students'),
  ('temporary_student.update', 'Update temporary students'),
  ('temporary_student.delete', 'Delete temporary students'),
  ('contact_person.read', 'View contact persons'),
  ('contact_person.create', 'Create contact persons'),
  ('contact_person.update', 'Update contact persons'),
  ('contact_person.delete', 'Delete contact persons'),
  ('faculty.read', 'View faculty'),
  ('faculty.create', 'Create faculty'),
  ('faculty.update', 'Update faculty'),
  ('faculty.delete', 'Delete faculty'),
  ('topic.read', 'View topics'),
  ('topic.create', 'Create topics'),
  ('topic.update', 'Update topics'),
  ('topic.delete', 'Delete topics'),
  ('university_mark.read', 'View university marks'),
  ('university_mark.create', 'Create university marks'),
  ('university_mark.update', 'Update university marks'),
  ('university_mark.delete', 'Delete university marks'),
  ('coding_question.read', 'View coding questions'),
  ('coding_question.create', 'Create coding questions'),
  ('coding_question.update', 'Update coding questions'),
  ('coding_question.delete', 'Delete coding questions'),
  ('compiler.read', 'View compiler endpoints'),
  ('compiler.submit', 'Submit code to compiler'),
  ('compiler_question_log.read', 'View compiler-question logs'),
  ('compiler_question_log.create', 'Create compiler-question log entries'),
  ('email.send', 'Send transactional email'),
  ('email.validate', 'Validate email addresses (OTP flow)'),
  ('student_institute_membership.read', 'View student-institute memberships'),
  ('student_institute_membership.create', 'Create student-institute memberships'),
  ('student_institute_membership.update', 'Update student-institute memberships'),
  ('student_institute_membership.delete', 'Delete student-institute memberships'),
  ('student_demographic_response.read', 'View student demographic responses'),
  ('student_demographic_response.create', 'Create student demographic responses'),
  ('student_demographic_response.update', 'Update student demographic responses'),
  ('student_demographic_response.delete', 'Delete student demographic responses'),
  ('demographic_field.read', 'View demographic fields'),
  ('demographic_field.create', 'Create demographic fields'),
  ('demographic_field.update', 'Update demographic fields'),
  ('demographic_field.delete', 'Delete demographic fields'),
  ('lead.read', 'View leads'),
  ('lead.create', 'Create leads'),
  ('lead.update', 'Update leads'),
  ('lead.delete', 'Delete leads'),
  ('live_tracking.read', 'View live-tracking events'),
  ('live_tracking.create', 'Create live-tracking events'),
  ('heartbeat.ping', 'Heartbeat ping (anonymous health probe)'),
  ('school_registration.read', 'View school registrations'),
  ('school_registration.create', 'Create school registrations'),
  ('school_registration.update', 'Update school registrations'),
  ('school_registration.delete', 'Delete school registrations'),
  ('career.read', 'View careers'),
  ('career.create', 'Create careers'),
  ('career.update', 'Update careers'),
  ('career.delete', 'Delete careers'),
  ('career_suggestion.read', 'View career suggestions'),
  ('career_suggestion.create', 'Create career suggestions'),
  ('career_suggestion.update', 'Update career suggestions'),
  ('career_suggestion.delete', 'Delete career suggestions'),
  ('communication_log.read', 'View communication logs'),
  ('communication_log.create', 'Create communication-log entries'),
  ('user_activity_log.read', 'View user activity logs'),
  ('user_activity_log.create', 'Create user activity log entries'),
  ('firebase_data_mapping.read', 'View Firebase data mappings'),
  ('firebase_data_mapping.create', 'Create Firebase data mappings'),
  ('firebase_data_mapping.update', 'Update Firebase data mappings'),
  ('firebase_data_mapping.delete', 'Delete Firebase data mappings'),
  ('counselling.availability_template.read', 'View counselling availability templates'),
  ('counselling.availability_template.create', 'Create counselling availability templates'),
  ('counselling.availability_template.update', 'Update counselling availability templates'),
  ('counselling.availability_template.delete', 'Delete counselling availability templates'),
  ('counselling.block_date.read', 'View counselling block-date requests'),
  ('counselling.block_date.create', 'Create counselling block-date requests'),
  ('counselling.block_date.update', 'Update counselling block-date requests'),
  ('counselling.block_date.delete', 'Delete counselling block-date requests'),
  ('counselling.activity_log.read', 'View counselling activity logs'),
  ('counselling.activity_log.create', 'Create counselling activity log entries'),
  ('counselling.appointment.read', 'View counselling appointments'),
  ('counselling.appointment.create', 'Create counselling appointments'),
  ('counselling.appointment.update', 'Update counselling appointments'),
  ('counselling.appointment.delete', 'Delete counselling appointments'),
  ('counselling.eligibility.read', 'View counselling eligibility records'),
  ('counselling.eligibility.create', 'Create counselling eligibility records'),
  ('counselling.eligibility.update', 'Update counselling eligibility records'),
  ('counselling.eligibility.delete', 'Delete counselling eligibility records'),
  ('counselling.rating.read', 'View counselling ratings'),
  ('counselling.rating.create', 'Create counselling ratings'),
  ('counselling.rating.update', 'Update counselling ratings'),
  ('counselling.rating.delete', 'Delete counselling ratings'),
  ('counselling.slot.read', 'View counselling slots'),
  ('counselling.slot.create', 'Create counselling slots'),
  ('counselling.slot.update', 'Update counselling slots'),
  ('counselling.slot.delete', 'Delete counselling slots'),
  ('counsellor.read', 'View counsellors'),
  ('counsellor.create', 'Create counsellors'),
  ('counsellor.update', 'Update counsellors'),
  ('counsellor.delete', 'Delete counsellors'),
  ('counsellor_institute_mapping.read', 'View counsellor-institute mappings'),
  ('counsellor_institute_mapping.create', 'Create counsellor-institute mappings'),
  ('counsellor_institute_mapping.update', 'Update counsellor-institute mappings'),
  ('counsellor_institute_mapping.delete', 'Delete counsellor-institute mappings'),
  ('counsellor_media.read', 'View counsellor media'),
  ('counsellor_media.create', 'Create counsellor media'),
  ('counsellor_media.update', 'Update counsellor media'),
  ('counsellor_media.delete', 'Delete counsellor media'),
  ('counselling.notification.read', 'View counselling notifications'),
  ('counselling.notification.create', 'Create counselling notifications'),
  ('counselling.notification.update', 'Update counselling notifications'),
  ('counselling.notification.delete', 'Delete counselling notifications'),
  ('counselling.session_notes.read', 'View counselling session notes'),
  ('counselling.session_notes.create', 'Create counselling session notes'),
  ('counselling.session_notes.update', 'Update counselling session notes'),
  ('counselling.session_notes.delete', 'Delete counselling session notes'),
  ('counselling.slot_configuration.read', 'View counselling slot configurations'),
  ('counselling.slot_configuration.create', 'Create counselling slot configurations'),
  ('counselling.slot_configuration.update', 'Update counselling slot configurations'),
  ('counselling.slot_configuration.delete', 'Delete counselling slot configurations'),
  ('counselling.student_counsellor_mapping.read', 'View student-counsellor mappings'),
  ('counselling.student_counsellor_mapping.create', 'Create student-counsellor mappings'),
  ('counselling.student_counsellor_mapping.update', 'Update student-counsellor mappings'),
  ('counselling.student_counsellor_mapping.delete', 'Delete student-counsellor mappings'),
  ('counselling.student_management.read', 'View counselling student management'),
  ('counselling.student_management.create', 'Create counselling student-management records'),
  ('counselling.student_management.update', 'Update counselling student-management records'),
  ('counselling.student_management.delete', 'Delete counselling student-management records')
ON DUPLICATE KEY UPDATE description = VALUES(description);
