name: career-nine-assessment
region: blr

static_sites:
  - name: assessment-frontend
    source_dir: /
    build_command: npm run build:production
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: VITE_API_URL
        value: https://api.career-9.com
        scope: BUILD_TIME
    routes:
      - path: /
    catchall_document: index.html

domains:
  - domain: assessment.career-9.com
    type: PRIMARY
