package com.kccitm.api.controller.career9.counselling;

import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.kccitm.api.exception.ResourceNotFoundException;
import com.kccitm.api.model.career9.counselling.Counsellor;
import com.kccitm.api.model.career9.counselling.SlotConfiguration;
import com.kccitm.api.repository.Career9.counselling.AvailabilityTemplateRepository;
import com.kccitm.api.repository.Career9.counselling.CounsellorRepository;
import com.kccitm.api.repository.Career9.counselling.CounsellingSlotRepository;
import com.kccitm.api.repository.Career9.counselling.SlotConfigurationRepository;
import com.kccitm.api.service.counselling.SlotMaterializationService;

@RestController
@RequestMapping("/api/slot-configuration")
public class SlotConfigurationController {

    private static final Logger logger = LoggerFactory.getLogger(SlotConfigurationController.class);

    @Autowired
    private SlotConfigurationRepository configRepository;

    @Autowired
    private CounsellorRepository counsellorRepository;

    @Autowired
    private CounsellingSlotRepository slotRepository;

    @Autowired
    private AvailabilityTemplateRepository templateRepository;

    @Autowired
    private SlotMaterializationService materializationService;

    /** Save a new slot configuration */
    // no scope arg: body is SlotConfiguration entity; admin-only
    @PreAuthorize("@auth.allows('counselling.slot_configuration.create')")
    @PostMapping("/create")
    public ResponseEntity<SlotConfiguration> create(@RequestBody SlotConfiguration config) {
        SlotConfiguration saved = configRepository.save(config);
        logger.info("Created slot configuration: {} (id={})", saved.getName(), saved.getId());
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    /** Get all saved configurations */
    // no scope arg: cross-counsellor admin list
    @PreAuthorize("@auth.allows('counselling.slot_configuration.read')")
    @GetMapping("/getAll")
    public ResponseEntity<List<SlotConfiguration>> getAll() {
        return ResponseEntity.ok(configRepository.findAllOrderByCreatedAtDesc());
    }

    /**
     * One-time cleanup: deletes all legacy AvailabilityTemplate rows and
     * auto-generated AVAILABLE slots. Booked/requested slots are preserved
     * (their template_id is nullified first to avoid FK violations).
     */
    // no scope arg: cleanup utility; admin-only
    @PreAuthorize("@auth.allows('counselling.slot_configuration.update')")
    @org.springframework.transaction.annotation.Transactional
    @org.springframework.web.bind.annotation.PostMapping("/cleanup-legacy")
    public ResponseEntity<?> cleanupLegacy() {
        try {
            // Step 1: Nullify template_id on ALL slots so we can delete templates safely
            int refsNullified = slotRepository.nullifyAllTemplateRefs();

            // Step 2: Delete AVAILABLE slots that were auto-generated (not manually created)
            int slotsDeleted = slotRepository.deleteAutoGeneratedAvailableSlots();

            // Step 3: Delete all availability templates
            long templatesDeleted = templateRepository.count();
            templateRepository.deleteAllInBatch();

            logger.info("Legacy cleanup: nullified {} refs, deleted {} slots, deleted {} templates",
                    refsNullified, slotsDeleted, templatesDeleted);

            return ResponseEntity.ok(Map.of(
                    "slotsDeleted", slotsDeleted,
                    "templatesDeleted", templatesDeleted,
                    "refsNullified", refsNullified));
        } catch (Exception e) {
            logger.error("Legacy cleanup failed", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", e.getMessage()));
        }
    }

    /** Delete a configuration */
    // no scope arg: delete by id; admin-only
    @PreAuthorize("@auth.allows('counselling.slot_configuration.delete')")
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<?> delete(@PathVariable Long id) {
        configRepository.deleteById(id);
        return ResponseEntity.ok().build();
    }

    /**
     * Apply a saved configuration to specific counsellors.
     * Generates actual CounsellingSlot rows for each counsellor
     * for every day in the config's date range.
     *
     * Body: { configId: Long, counsellorIds: [Long] }
     */
    // no scope arg: body is raw Map; admin applies config to counsellors
    @PreAuthorize("@auth.allows('counselling.slot_configuration.update')")
    @SuppressWarnings("unchecked")
    @PostMapping("/apply")
    public ResponseEntity<?> applyToCounsellors(@RequestBody Map<String, Object> body) {
        Long configId = ((Number) body.get("configId")).longValue();
        List<Number> idList = (List<Number>) body.get("counsellorIds");

        SlotConfiguration config = configRepository.findById(configId)
                .orElseThrow(() -> new ResourceNotFoundException("SlotConfiguration", "id", configId));

        int totalSlots = 0;
        int totalSkipped = 0;
        int counsellorsProcessed = 0;

        for (Number idNum : idList) {
            Long counsellorId = idNum.longValue();
            Counsellor counsellor = counsellorRepository.findById(counsellorId).orElse(null);
            if (counsellor == null) continue;

            // Slot rows are built by SlotMaterializationService, the same class the
            // availability-template path uses, so both routes into the calendar create
            // slots identically and share one definition of "this time is already taken".
            SlotMaterializationService.MaterializationResult result =
                    materializationService.materializeForConfiguration(counsellor, config);
            totalSlots += result.created;
            totalSkipped += result.skipped;
            counsellorsProcessed++;
        }

        logger.info("Applied config {} to {} counsellors, created {} slots, skipped {} for conflicts",
                configId, counsellorsProcessed, totalSlots, totalSkipped);

        return ResponseEntity.ok(Map.of(
                "counsellorsProcessed", counsellorsProcessed,
                "totalSlots", totalSlots));
    }
}
