// CollegeDetailModal.tsx
import React, { useState, useEffect } from "react";
import { Modal } from "react-bootstrap-v5";
import UseAnimations from "react-useanimations";
import menu2 from "react-useanimations/lib/menu2";
import {CreateSessionData} from "../API/College_APIs";
type CollegeDataForModal = {
  instituteCode?: string;
  instituteName?: string;
  [key: string]: any;
};

type Props = {
  show: boolean;
  onHide: (v?: boolean) => void;
  setPageLoading: (v: any) => void;
  data?: CollegeDataForModal;
};

type SessionData = {
  sessionName: string;
  grades: {
    gradeName: string;
    sections: string[];
  }[];
};

const CollegeDetailModal = (props: Props) => {
  const [loading, setLoading] = useState(false);
  
  // Dropdown states
  const [sessionDropdownOpen, setSessionDropdownOpen] = useState(false);
  const [gradeDropdownOpen, setGradeDropdownOpen] = useState(false);
  const [sectionDropdownOpen, setSectionDropdownOpen] = useState(false);

  // Main data structure - array of sessions with their grades and sections
  const [sessionsData, setSessionsData] = useState<SessionData[]>([]);

  // Input states
  const [newSessionInput, setNewSessionInput] = useState("");
  const [newGradeInput, setNewGradeInput] = useState("");
  const [newSectionInput, setNewSectionInput] = useState("");

  // Currently working with
  const [currentSessionIndex, setCurrentSessionIndex] = useState<number | null>(null);
  const [currentGradeIndex, setCurrentGradeIndex] = useState<number | null>(null);

  // Reset all state when modal opens/closes or institute changes
  useEffect(() => {
    if (props.show) {
      // Reset all states when modal opens
      setSessionsData([]);
      setNewSessionInput("");
      setNewGradeInput("");
      setNewSectionInput("");
      setCurrentSessionIndex(null);
      setCurrentGradeIndex(null);
      setSessionDropdownOpen(false);
      setGradeDropdownOpen(false);
      setSectionDropdownOpen(false);

      // TODO: Load institute-specific data here
      // Example: fetchInstituteData(props.data?.instituteCode);
    }
  }, [props.show, props.data?.instituteCode]);

  // Add new session
  const handleAddSession = () => {
    if (newSessionInput.trim()) {
      const sessionExists = sessionsData.some(s => s.sessionName === newSessionInput.trim());
      if (!sessionExists) {
        setSessionsData([...sessionsData, {
          sessionName: newSessionInput.trim(),
          grades: []
        }]);
        setNewSessionInput("");
      }
    }
  };

  // Select a session to work with
  const handleSelectSession = (index: number) => {
    setCurrentSessionIndex(index);
    setCurrentGradeIndex(null); // Reset grade selection when session changes
    setSessionDropdownOpen(false);
    // Note: We don't close gradeDropdownOpen here so grades remain visible
  };

  // Add new grade to current session
  const handleAddGrade = () => {
    if (currentSessionIndex !== null && newGradeInput.trim()) {
      const updatedSessions = [...sessionsData];
      const currentSession = updatedSessions[currentSessionIndex];
      
      const gradeExists = currentSession.grades.some(g => g.gradeName === newGradeInput.trim());
      if (!gradeExists) {
        currentSession.grades.push({
          gradeName: newGradeInput.trim(),
          sections: []
        });
        setSessionsData(updatedSessions);
        setNewGradeInput("");
      }
    }
  };

  // Select a grade to work with
  const handleSelectGrade = (gradeIndex: number) => {
    setCurrentGradeIndex(gradeIndex);
    setGradeDropdownOpen(false);
  };

  // Add new section to current grade
  const handleAddSection = () => {
    if (currentSessionIndex !== null && currentGradeIndex !== null && newSectionInput.trim()) {
      const updatedSessions = [...sessionsData];
      const currentGrade = updatedSessions[currentSessionIndex].grades[currentGradeIndex];
      
      if (!currentGrade.sections.includes(newSectionInput.trim())) {
        currentGrade.sections.push(newSectionInput.trim());
        setSessionsData(updatedSessions);
        setNewSectionInput("");
      }
    }
  };

  // Remove a section
  const handleRemoveSection = (sectionIndex: number) => {
    if (currentSessionIndex !== null && currentGradeIndex !== null) {
      const updatedSessions = [...sessionsData];
      updatedSessions[currentSessionIndex].grades[currentGradeIndex].sections.splice(sectionIndex, 1);
      setSessionsData(updatedSessions);
    }
  };

  const handleClose = () => {
    props.onHide();
  };

  const handleSubmit = async () => {
    try {
      setLoading(true);
      
      // Transform the data to match the API format (IDs will be auto-generated by backend)
      const formattedOutput = sessionsData.map((session) => ({
        sessionYear: session.sessionName,
        schoolClasses: session.grades.map((grade) => ({
          className: grade.gradeName,
          schoolSections: grade.sections.map((section) => ({
            sectionName: section
          }))
        })),
        institute_code: props.data?.instituteCode || null
      }));

      console.log("Formatted API JSON:");
      console.log(formattedOutput);
      
      // Single line for easy copying
      // console.log("Single line JSON:", JSON.stringify(formattedOutput));
      await CreateSessionData(formattedOutput);

      props.onHide();
      
    } catch (error) {
      console.error('Error submitting data:', error);
      alert('Failed to submit institute hierarchy. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // Get current session name
  const getCurrentSessionName = () => {
    if (currentSessionIndex !== null) {
      return sessionsData[currentSessionIndex]?.sessionName;
    }
    return null;
  };

  // Get current grade name
  const getCurrentGradeName = () => {
    if (currentSessionIndex !== null && currentGradeIndex !== null) {
      return sessionsData[currentSessionIndex]?.grades[currentGradeIndex]?.gradeName;
    }
    return null;
  };

  // Get current sections
  const getCurrentSections = () => {
    if (currentSessionIndex !== null && currentGradeIndex !== null) {
      return sessionsData[currentSessionIndex]?.grades[currentGradeIndex]?.sections || [];
    }
    return [];
  };

  return (
    <Modal
      show={props.show}
      onHide={() => props.onHide()}
      centered
      size="xl"
      className="college-modal"
      aria-labelledby="college-detail-modal-title"
      style={{ maxHeight: '90vh' }}
    >
      <style>{`
        .college-modal .modal-dialog {
          max-width: 1200px;
          height: 85vh;
        }
        
        .college-modal .modal-content {
          height: 100%;
          display: flex;
          flex-direction: column;
        }
        
        .college-modal .modal-body {
          flex: 1;
          overflow-y: auto;
          max-height: calc(85vh - 180px);
        }
        
        .college-modal .dropdown-menu {
          max-height: 350px;
        }
      `}</style>
      <Modal.Header className="border-0 pb-0">
        <div className="d-flex flex-column">
          <h3 id="college-detail-modal-title" className="mb-1 fw-bold">
            Institute Details
          </h3>
          <span className="text-muted small">
            {props.data?.instituteName && (
              <span className="fw-semibold me-2">{props.data.instituteName}</span>
            )}
            Manage institute information, mappings, and configurations
          </span>
        </div>

        <div
          className="btn btn-sm btn-icon btn-light ms-3"
          onClick={() => props.onHide()}
          style={{ cursor: "pointer" }}
        >
          <UseAnimations animation={menu2} size={24} strokeColor={"#181C32"} reverse />
        </div>
      </Modal.Header>

      <div className="form w-100">
        <Modal.Body className="pt-3">
          <div className="d-flex flex-column gap-4">
            {/* ====== ACTION BUTTONS SECTION ====== */}
            <div className="card shadow-sm border-0" style={{ background: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%)', minHeight: '500px' }}>
              <div className="card-body" style={{ minHeight: '480px' }}>
                <div className="mb-3">
                  <h5 className="mb-1 fw-semibold">Quick Actions</h5>
                  <small className="text-muted">
                    Add sessions, grades, and sections for this institute
                  </small>
                </div>

                <div className="d-flex flex-column gap-3">
                  {/* Add Session Dropdown */}
                  <div className="position-relative">
                    <button
                      type="button"
                      className="btn btn-primary dropdown-toggle d-flex align-items-center justify-content-between gap-2 w-100"
                      onClick={() => {
                        setSessionDropdownOpen(!sessionDropdownOpen);
                        setGradeDropdownOpen(false);
                        setSectionDropdownOpen(false);
                      }}
                    >
                      <div className="d-flex align-items-center gap-2">
                        <i className="bi bi-calendar-plus"></i>
                        <span>{getCurrentSessionName() || "Select/Add Session"}</span>
                      </div>
                    </button>
                    {sessionDropdownOpen && (
                      <div
                        className="dropdown-menu show w-100 p-3 shadow-lg"
                        style={{ minWidth: '100%', maxHeight: '350px', overflowY: 'auto', position: 'absolute', zIndex: 1000 }}
                      >
                        {/* Add new session input */}
                        <div className="mb-3">
                          <label className="form-label small fw-semibold">Add New Session</label>
                          <div className="input-group">
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter session name (e.g., 2024-25)"
                              value={newSessionInput}
                              onChange={(e) => setNewSessionInput(e.target.value)}
                              onKeyPress={(e) => {
                                if (e.key === 'Enter') {
                                  handleAddSession();
                                  e.preventDefault();
                                }
                              }}
                            />
                            <button
                              type="button"
                              className="btn btn-primary"
                              onClick={handleAddSession}
                              disabled={!newSessionInput.trim()}
                            >
                              <i className="bi bi-plus-lg"></i>
                            </button>
                          </div>
                        </div>

                        {/* List of sessions */}
                        {sessionsData.length > 0 && (
                          <>
                            <div className="dropdown-divider"></div>
                            <label className="form-label small fw-semibold">Existing Sessions</label>
                            <div className="list-group">
                              {sessionsData.map((session, index) => (
                                <button
                                  key={index}
                                  type="button"
                                  className={`list-group-item list-group-item-action ${currentSessionIndex === index ? 'active' : ''}`}
                                  onClick={() => handleSelectSession(index)}
                                >
                                  <div className="d-flex justify-content-between align-items-center">
                                    <span>{session.sessionName}</span>
                                    <span className="badge bg-secondary">{session.grades.length} grades</span>
                                  </div>
                                </button>
                              ))}
                            </div>
                          </>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Add Grade Dropdown */}
                  <div className="position-relative">
                    <button
                      type="button"
                      className="btn btn-success dropdown-toggle d-flex align-items-center justify-content-between gap-2 w-100"
                      onClick={() => {
                        if (currentSessionIndex !== null) {
                          setGradeDropdownOpen(!gradeDropdownOpen);
                          setSessionDropdownOpen(false);
                          setSectionDropdownOpen(false);
                        }
                      }}
                      disabled={currentSessionIndex === null}
                    >
                      <div className="d-flex align-items-center gap-2">
                        <i className="bi bi-award"></i>
                        <span>{getCurrentGradeName() || "Select/Add Grade"}</span>
                        {currentSessionIndex !== null && sessionsData[currentSessionIndex]?.grades.length > 0 && (
                          <span className="badge bg-light text-success ms-2">
                            {sessionsData[currentSessionIndex].grades.length} grades
                          </span>
                        )}
                        {currentSessionIndex === null && <small className="ms-2 text-light">(Select session first)</small>}
                      </div>
                    </button>
                    {gradeDropdownOpen && currentSessionIndex !== null && (
                      <div
                        className="dropdown-menu show w-100 p-3 shadow-lg"
                        style={{ minWidth: '100%', maxHeight: '350px', overflowY: 'auto', position: 'absolute', zIndex: 1000 }}
                      >
                        {/* Add new grade input */}
                        <div className="mb-3">
                          <label className="form-label small fw-semibold">
                            Add Grade to "{getCurrentSessionName()}"
                          </label>
                          <div className="input-group">
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter grade name (e.g., Class 9)"
                              value={newGradeInput}
                              onChange={(e) => setNewGradeInput(e.target.value)}
                              onKeyPress={(e) => {
                                if (e.key === 'Enter') {
                                  handleAddGrade();
                                  e.preventDefault();
                                }
                              }}
                            />
                            <button
                              type="button"
                              className="btn btn-success"
                              onClick={handleAddGrade}
                              disabled={!newGradeInput.trim()}
                            >
                              <i className="bi bi-plus-lg"></i>
                            </button>
                          </div>
                        </div>

                        {/* List of grades for selected session */}
                        {sessionsData[currentSessionIndex]?.grades.length > 0 ? (
                          <>
                            <div className="dropdown-divider"></div>
                            <label className="form-label small fw-semibold">
                              Grades in "{getCurrentSessionName()}"
                            </label>
                            <div className="list-group">
                              {sessionsData[currentSessionIndex].grades.map((grade, index) => (
                                <button
                                  key={index}
                                  type="button"
                                  className={`list-group-item list-group-item-action ${currentGradeIndex === index ? 'active' : ''}`}
                                  onClick={() => handleSelectGrade(index)}
                                >
                                  <div className="d-flex justify-content-between align-items-center">
                                    <span>{grade.gradeName}</span>
                                    <span className="badge bg-secondary">{grade.sections.length} sections</span>
                                  </div>
                                </button>
                              ))}
                            </div>
                          </>
                        ) : (
                          <>
                            <div className="dropdown-divider"></div>
                            <div className="text-center text-muted py-2">
                              <i className="bi bi-inbox"></i>
                              <p className="mb-0 small">No grades added yet for this session</p>
                            </div>
                          </>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Add Section Dropdown */}
                  <div className="position-relative">
                    <button
                      type="button"
                      className="btn btn-info dropdown-toggle d-flex align-items-center justify-content-between gap-2 w-100"
                      onClick={() => {
                        if (currentGradeIndex !== null) {
                          setSectionDropdownOpen(!sectionDropdownOpen);
                          setSessionDropdownOpen(false);
                          setGradeDropdownOpen(false);
                        }
                      }}
                      disabled={currentGradeIndex === null}
                    >
                      <div className="d-flex align-items-center gap-2">
                        <i className="bi bi-grid-3x3"></i>
                        <span>Add/View Sections</span>
                        {currentGradeIndex !== null && getCurrentSections().length > 0 && (
                          <span className="badge bg-light text-info ms-2">
                            {getCurrentSections().length} sections
                          </span>
                        )}
                        {currentGradeIndex === null && <small className="ms-2 text-light">(Select grade first)</small>}
                      </div>
                    </button>
                    {sectionDropdownOpen && currentGradeIndex !== null && (
                      <div
                        className="dropdown-menu show w-100 p-3 shadow-lg"
                        style={{ minWidth: '100%', maxHeight: '350px', overflowY: 'auto', position: 'absolute', zIndex: 1000 }}
                      >
                        {/* Add new section input */}
                        <div className="mb-3">
                          <label className="form-label small fw-semibold">
                            Add Section to "{getCurrentGradeName()}"
                          </label>
                          <div className="input-group">
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter section name (e.g., A, B, C)"
                              value={newSectionInput}
                              onChange={(e) => setNewSectionInput(e.target.value)}
                              onKeyPress={(e) => {
                                if (e.key === 'Enter') {
                                  handleAddSection();
                                  e.preventDefault();
                                }
                              }}
                            />
                            <button
                              type="button"
                              className="btn btn-info"
                              onClick={handleAddSection}
                              disabled={!newSectionInput.trim()}
                            >
                              <i className="bi bi-plus-lg"></i>
                            </button>
                          </div>
                        </div>

                        {/* List of sections */}
                        {getCurrentSections().length > 0 ? (
                          <>
                            <div className="dropdown-divider"></div>
                            <label className="form-label small fw-semibold">Sections in "{getCurrentGradeName()}"</label>
                            <div className="list-group">
                              {getCurrentSections().map((section, index) => (
                                <div
                                  key={index}
                                  className="list-group-item d-flex justify-content-between align-items-center"
                                >
                                  <span>{section}</span>
                                  <button
                                    type="button"
                                    className="btn btn-sm btn-danger"
                                    onClick={() => handleRemoveSection(index)}
                                  >
                                    <i className="bi bi-trash"></i>
                                  </button>
                                </div>
                              ))}
                            </div>
                          </>
                        ) : (
                          <>
                            <div className="dropdown-divider"></div>
                            <div className="text-center text-muted py-2">
                              <i className="bi bi-inbox"></i>
                              <p className="mb-0 small">No sections added yet for this grade</p>
                            </div>
                          </>
                        )}
                      </div>
                    )}
                  </div>
                </div>

                {/* Complete Summary Section */}
                {sessionsData.length > 0 && (
                  <div className="mt-4 p-3 bg-white rounded border">
                    <h6 className="mb-3 fw-semibold d-flex align-items-center gap-2">
                      <i className="bi bi-list-check"></i>
                      Complete Institute Structure
                    </h6>
                    <div className="d-flex flex-column gap-3">
                      {sessionsData.map((session, sessionIdx) => (
                        <div key={sessionIdx} className="border rounded p-3">
                          <div className="d-flex align-items-center gap-2 mb-2">
                            <span className="badge bg-primary px-3 py-2">
                              <i className="bi bi-calendar3 me-1"></i>
                              {session.sessionName}
                            </span>
                            <small className="text-muted">({session.grades.length} grades)</small>
                          </div>
                          
                          {session.grades.length > 0 && (
                            <div className="ms-3 mt-2">
                              {session.grades.map((grade, gradeIdx) => (
                                <div key={gradeIdx} className="mb-2">
                                  <div className="d-flex align-items-center gap-2 mb-1">
                                    <i className="bi bi-arrow-return-right text-muted"></i>
                                    <span className="badge bg-success">
                                      <i className="bi bi-award me-1"></i>
                                      {grade.gradeName}
                                    </span>
                                    <small className="text-muted">({grade.sections.length} sections)</small>
                                  </div>
                                  
                                  {grade.sections.length > 0 && (
                                    <div className="ms-4 d-flex flex-wrap gap-1">
                                      {grade.sections.map((section, sectionIdx) => (
                                        <span key={sectionIdx} className="badge bg-info-subtle text-info">
                                          Section {section}
                                        </span>
                                      ))}
                                    </div>
                                  )}
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </Modal.Body>

        <Modal.Footer className="border-0 pt-0">
          <div className="d-flex justify-content-between w-100 align-items-center">
            <div className="text-muted small">
              {props.data?.instituteCode && (
                <>
                  <span className="fw-semibold">Institute Code: </span>
                  <span>{props.data.instituteCode}</span>
                </>
              )}
            </div>

            <div className="d-flex gap-2">
              <button
                type="button"
                className="btn btn-sm btn-light"
                onClick={handleClose}
                disabled={loading}
              >
                Close
              </button>
              
              <button
                type="button"
                className="btn btn-sm btn-primary"
                onClick={handleSubmit}
                disabled={loading || sessionsData.length === 0}
              >
                {!loading && (
                  <span className="d-flex align-items-center gap-1">
                    <i className="bi bi-check-circle"></i>
                    Submit
                  </span>
                )}
                {loading && (
                  <span className="d-flex align-items-center gap-2">
                    <span className="spinner-border spinner-border-sm" />
                    Submitting...
                  </span>
                )}
              </button>
            </div>
          </div>
        </Modal.Footer>
      </div>
    </Modal>
  );
};

export default CollegeDetailModal;