package com.kccitm.api.repository.Career9.counselling;

import java.time.LocalDate;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.kccitm.api.model.career9.counselling.CounsellingSlot;

@Repository
public interface CounsellingSlotRepository extends JpaRepository<CounsellingSlot, Long> {

    List<CounsellingSlot> findByStatusAndDateBetween(String status, LocalDate start, LocalDate end);

    List<CounsellingSlot> findByCounsellorIdAndDateBetween(Long counsellorId, LocalDate start, LocalDate end);

    List<CounsellingSlot> findByCounsellorId(Long counsellorId);

    @Query("SELECT s FROM CounsellingSlot s WHERE s.status = 'AVAILABLE' AND s.isBlocked = false AND s.date BETWEEN :start AND :end ORDER BY s.date, s.startTime")
    List<CounsellingSlot> findAvailableSlots(@Param("start") LocalDate start, @Param("end") LocalDate end);

    @Query("SELECT s FROM CounsellingSlot s WHERE s.counsellor.id = :counsellorId AND s.date = :date AND s.template.id = :templateId")
    List<CounsellingSlot> findByCounsellorIdAndDateAndTemplateId(
            @Param("counsellorId") Long counsellorId,
            @Param("date") LocalDate date,
            @Param("templateId") Long templateId);

    List<CounsellingSlot> findByCounsellorIdAndDateAndIsBlockedTrue(Long counsellorId, LocalDate date);

    /** Find available slots for a specific set of counsellors (institute-filtered) */
    @Query("SELECT s FROM CounsellingSlot s WHERE s.status = 'AVAILABLE' AND s.isBlocked = false "
         + "AND s.counsellor.id IN :counsellorIds AND s.date BETWEEN :start AND :end "
         + "ORDER BY s.date, s.startTime")
    List<CounsellingSlot> findAvailableSlotsForCounsellors(
            @Param("counsellorIds") List<Long> counsellorIds,
            @Param("start") LocalDate start,
            @Param("end") LocalDate end);

    /** Nullify template_id on every slot — needed before deleting templates */
    @Modifying
    @Transactional
    @Query(value = "UPDATE counselling_slot SET template_id = NULL WHERE template_id IS NOT NULL", nativeQuery = true)
    int nullifyAllTemplateRefs();

    /** Bulk delete all AVAILABLE slots that were auto-generated (had a template ref) */
    @Modifying
    @Transactional
    @Query(value = "DELETE FROM counselling_slot WHERE status = 'AVAILABLE' AND is_manually_created = FALSE", nativeQuery = true)
    int deleteAutoGeneratedAvailableSlots();
}
