import type React from "react"

/**
 * Inline style tokens shared by the four registration pages. The page shell
 * (background, header, card, grid) lives in register.css / RegisterShell; these
 * are the per-element styles the pages spread onto inputs, labels and buttons.
 *
 * Inputs keep a 16px font so iOS Safari does not zoom on focus; the padding is
 * what makes them compact (~43px tall).
 */
export const rs: { [key: string]: React.CSSProperties } = {
  sectionTitle: {
    fontSize: "0.74rem",
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    margin: "0 0 10px",
  },
  selectionLabel: {
    fontSize: "0.68rem",
    fontWeight: 700,
    color: "#10b981",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: 6,
  },
  waiting: {
    margin: 0,
    padding: "12px 16px",
    border: "1.5px dashed #e2e8f0",
    borderRadius: 12,
    color: "#64748b",
    fontSize: "0.86rem",
  },
  label: {
    display: "block",
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "#374151",
    marginBottom: 5,
  },
  input: {
    width: "100%",
    padding: "9px 14px",
    borderRadius: 10,
    border: "1.5px solid #e2e8f0",
    background: "rgba(255, 255, 255, 0.9)",
    fontSize: 16,
    color: "#1e293b",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  inputFocus: {
    borderColor: "#34d399",
    boxShadow: "0 0 0 3px rgba(52, 211, 153, 0.15)",
  },
  readonlyValue: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 10,
    border: "1.5px solid #e2e8f0",
    background: "rgba(241, 245, 249, 0.7)",
    fontSize: "0.92rem",
    color: "#1e293b",
    boxSizing: "border-box",
    fontWeight: 600,
  },
  btnPrimary: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "11px 24px",
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg, #10b981 0%, #059669 50%, #047857 100%)",
    color: "#fff",
    fontSize: "0.92rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 16px rgba(16, 185, 129, 0.35), 0 1px 3px rgba(0, 0, 0, 0.1)",
    transition: "transform 0.15s, box-shadow 0.15s",
    letterSpacing: "0.01em",
    fontFamily: "inherit",
    whiteSpace: "nowrap",
  },
  btnOutline: {
    padding: "10px 16px",
    borderRadius: 10,
    border: "1.5px solid #10b981",
    background: "transparent",
    color: "#059669",
    fontSize: "0.86rem",
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.15s",
    fontFamily: "inherit",
  },
  priceBadge: {
    display: "inline-flex",
    alignItems: "center",
    background: "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)",
    color: "#065f46",
    padding: "6px 14px",
    borderRadius: 10,
    fontSize: "0.9rem",
    fontWeight: 700,
    border: "1px solid #6ee7b7",
  },
  spinner: {
    width: 32,
    height: 32,
    border: "3px solid #e2e8f0",
    borderTopColor: "#10b981",
    borderRadius: "50%",
    animation: "reg-spin 0.8s linear infinite",
  },
  errorBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "12px 14px",
    background: "#fff5f5",
    border: "1px solid #fecaca",
    borderRadius: 12,
    borderBottom: "3px solid #fecaca",
    color: "#374151",
    fontSize: "0.9rem",
    lineHeight: 1.5,
    position: "relative",
  },
  errorBannerIcon: {
    flex: "0 0 auto",
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: "#ef4444",
    color: "#fff",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  errorBannerText: {
    flex: "1 1 auto",
    paddingRight: 24,
    color: "#374151",
  },
  errorBannerClose: {
    position: "absolute",
    top: 6,
    right: 8,
    border: "none",
    background: "transparent",
    fontSize: "1.4rem",
    lineHeight: 1,
    color: "#9ca3af",
    cursor: "pointer",
    padding: "4px 8px",
  },
}

/** Blur handler counterpart to `rs.inputFocus` — resets the focus ring. */
export const inputBlurStyle: React.CSSProperties = { borderColor: "#e2e8f0", boxShadow: "none" }
