package com.kccitm.api.service.career9;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.kccitm.api.controller.StudentInfoController;
import com.kccitm.api.security.UserPrincipal;
import com.kccitm.api.model.career9.AssessmentTable;
import com.kccitm.api.model.career9.GeneratedReport;
import com.kccitm.api.model.career9.StudentInfo;
import com.kccitm.api.model.career9.counselling.CounsellingAppointment;
import com.kccitm.api.model.career9.counselling.Counsellor;
import com.kccitm.api.model.career9.school.InstituteDetail;
import com.kccitm.api.repository.Career9.AssessmentTableRepository;
import com.kccitm.api.repository.Career9.GeneratedReportRepository;
import com.kccitm.api.repository.Career9.counselling.CounsellingAppointmentRepository;
import com.kccitm.api.repository.Career9.counselling.CounsellingRatingRepository;
import com.kccitm.api.repository.Career9.counselling.CounsellorRepository;
import com.kccitm.api.repository.InstituteDetailRepository;
import com.kccitm.api.security.access.AccessScope;
import com.kccitm.api.security.access.AccessScopeJpqlBuilder;
import com.kccitm.api.security.access.AccessScopeJpqlBuilder.Fields;
import com.kccitm.api.security.access.AccessScopeService;

/**
 * Single source of truth for the admin-dashboard data. Replaces the previous
 * cached-snapshot + in-memory filter pipeline with one method per list, each
 * either fetching the unfiltered set (super-admin) or running a scoped JPQL
 * query keyed on the caller's {@link AccessScope}.
 *
 * <p>Three branches per request:
 * <ol>
 *   <li><b>Super-admin</b> ({@code AccessScopeService.forCurrentUser()} returns
 *       {@code Optional.empty()}) — every list runs its unfiltered variant via
 *       the existing {@code findAll()} methods. Same behaviour as today's raw
 *       snapshot, just without the 24 h cache.</li>
 *   <li><b>No mappings</b> (non-super-admin with empty AccessScope) — every
 *       list returns an empty array. Deny-by-default.</li>
 *   <li><b>Scoped</b> — each list runs a JPQL query whose {@code WHERE} is
 *       generated by {@link AccessScopeJpqlBuilder} from the user's scope
 *       rules. JOIN paths are documented per-method below.</li>
 * </ol>
 */
@Service
public class DashboardDataService {

    private static final Logger log = LoggerFactory.getLogger(DashboardDataService.class);

    /** Redis key prefix for per-user cached dashboard payloads. */
    private static final String CACHE_KEY_PREFIX = "dashboard:user:";

    /** Cache TTL — user-confirmed 24 h. Staleness is surfaced to the FE via the
     *  {@code computedAt} field so the UI can show "updated X ago". */
    private static final Duration CACHE_TTL = Duration.ofHours(24);

    @PersistenceContext
    private EntityManager em;

    @Autowired private AccessScopeService accessScopeService;
    @Autowired(required = false) private StringRedisTemplate stringRedisTemplate;
    @Autowired private ObjectMapper objectMapper;
    @Autowired private StudentInfoController studentInfoController;
    @Autowired private InstituteDetailRepository instituteDetailRepository;
    @Autowired private CounsellorRepository counsellorRepository;
    @Autowired private CounsellingAppointmentRepository appointmentRepository;
    @Autowired private CounsellingRatingRepository ratingRepository;
    @Autowired private AssessmentTableRepository assessmentTableRepository;
    @Autowired private GeneratedReportRepository generatedReportRepository;

    /**
     * Build (or fetch from cache) the dashboard payload for the currently
     * authenticated principal. Cache is per-user with a 24 h TTL; staleness is
     * surfaced to the FE via {@code computedAt} so the UI can show "updated X
     * ago". Cache reads fail soft — if Redis is unreachable, we just compute
     * fresh and skip the SET.
     */
    @Transactional(readOnly = true)
    public Map<String, Object> fetchForCurrentUser() {
        Long userId = currentUserId();
        Map<String, Object> cached = userId == null ? null : readCache(userId);
        if (cached != null) {
            cached.put("cacheHit", true);
            return cached;
        }
        Map<String, Object> fresh = compute();
        fresh.put("cacheHit", false);
        if (userId != null) writeCache(userId, fresh);
        return fresh;
    }

    /**
     * Force-recompute path used by {@code POST /admin/snapshot/refresh}. Busts
     * the user's cache key first, then fetches (which will miss → compute →
     * re-cache). Same shape as {@link #fetchForCurrentUser()} so the FE can
     * call either endpoint interchangeably.
     */
    @Transactional(readOnly = true)
    public Map<String, Object> refreshForCurrentUser() {
        Long userId = currentUserId();
        if (userId != null) invalidateCache(userId);
        return fetchForCurrentUser();
    }

    /**
     * Compute the payload directly from the DB (no cache). Public so callers
     * that explicitly want fresh data (e.g., system jobs) can bypass the
     * cache without touching it. Output shape matches the legacy snapshot:
     * 8 list-valued keys plus {@code computedAt} and {@code __accessScope}.
     */
    @Transactional(readOnly = true)
    public Map<String, Object> compute() {
        Optional<AccessScope> scopeOpt = accessScopeService.forCurrentUser();
        Map<String, Object> out = new LinkedHashMap<>();

        if (!scopeOpt.isPresent()) {
            // Super-admin: full payload, no filtering.
            fillForSuperAdmin(out);
        } else {
            AccessScope scope = scopeOpt.get();
            if (scope.isEmpty()) {
                fillEmpty(out);
                stampScopeMeta(out, scope);
            } else {
                fillScoped(out, scope);
                stampScopeMeta(out, scope);
            }
        }

        out.put("computedAt", Instant.now().toString());
        return out;
    }

    // ─── Redis cache helpers ────────────────────────────────────────────

    private Long currentUserId() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth == null || !(auth.getPrincipal() instanceof UserPrincipal)) return null;
        return ((UserPrincipal) auth.getPrincipal()).getId();
    }

    private String cacheKey(Long userId) {
        return CACHE_KEY_PREFIX + userId;
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> readCache(Long userId) {
        if (stringRedisTemplate == null) return null;
        try {
            String json = stringRedisTemplate.opsForValue().get(cacheKey(userId));
            if (json == null) return null;
            return objectMapper.readValue(json, Map.class);
        } catch (Exception e) {
            log.warn("Dashboard cache read failed for user={} — falling through to compute: {}",
                    userId, e.getMessage());
            return null;
        }
    }

    private void writeCache(Long userId, Map<String, Object> payload) {
        if (stringRedisTemplate == null) return;
        try {
            String json = objectMapper.writeValueAsString(payload);
            stringRedisTemplate.opsForValue().set(cacheKey(userId), json, CACHE_TTL);
        } catch (Exception e) {
            // Cache writes are best-effort; payload was already returned to the caller.
            log.warn("Dashboard cache write failed for user={}: {}", userId, e.getMessage());
        }
    }

    /** Public so other write paths (Map-to-College, access-level CRUD) can
     *  bust a specific user's cache on update if they want fresher data than
     *  the 24 h TTL allows. Not wired into those paths yet. */
    public void invalidateCache(Long userId) {
        if (stringRedisTemplate == null || userId == null) return;
        try {
            stringRedisTemplate.delete(cacheKey(userId));
        } catch (Exception e) {
            log.warn("Dashboard cache delete failed for user={}: {}", userId, e.getMessage());
        }
    }

    // ─── Branch 1: super-admin ───────────────────────────────────────────

    private void fillForSuperAdmin(Map<String, Object> out) {
        List<StudentInfo> students = safeCall(() -> studentInfoController.getAllStudentInfo(), Collections.<StudentInfo>emptyList());
        out.put("students", students);
        out.put("studentMappings", safeCall(() -> studentInfoController.assembleStudentsWithMapping(students), Collections.<Map<String, Object>>emptyList()));
        out.put("institutes", safeCall(() -> instituteDetailRepository.findByDisplay(true), Collections.<InstituteDetail>emptyList()));
        out.put("counsellors", safeCall(() -> counsellorRepository.findAll(), Collections.<Counsellor>emptyList()));
        out.put("appointments", safeCall(() -> appointmentRepository.findAll(), Collections.<CounsellingAppointment>emptyList()));
        out.put("ratingSummary", safeCall(this::ratingSummaryUnscoped, Collections.<Map<String, Object>>emptyList()));
        out.put("assessments", safeCall(() -> assessmentTableRepository.findAll(), Collections.<AssessmentTable>emptyList()));
        out.put("reports", safeCall(() -> generatedReportRepository.findAll(), Collections.<GeneratedReport>emptyList()));
    }

    private List<Map<String, Object>> ratingSummaryUnscoped() {
        // Mirrors CounsellingRatingController.summaryByCounsellor() shape.
        List<Object[]> rows = ratingRepository.summaryByCounsellor();
        return mapRatingRows(rows);
    }

    // ─── Branch 2: empty scope (no mappings) ─────────────────────────────

    private void fillEmpty(Map<String, Object> out) {
        out.put("students", Collections.<StudentInfo>emptyList());
        out.put("studentMappings", Collections.<Map<String, Object>>emptyList());
        out.put("institutes", Collections.<InstituteDetail>emptyList());
        out.put("counsellors", Collections.<Counsellor>emptyList());
        out.put("appointments", Collections.<CounsellingAppointment>emptyList());
        out.put("ratingSummary", Collections.<Map<String, Object>>emptyList());
        out.put("assessments", Collections.<AssessmentTable>emptyList());
        out.put("reports", Collections.<GeneratedReport>emptyList());
    }

    // ─── Branch 3: scoped queries ────────────────────────────────────────

    private void fillScoped(Map<String, Object> out, AccessScope scope) {
        // 1. students — direct columns on StudentInfo.
        List<StudentInfo> students = safeCall(() -> queryStudents(scope), Collections.<StudentInfo>emptyList());
        out.put("students", students);

        // 2. studentMappings — same student set, assembled into the rich shape.
        out.put("studentMappings", safeCall(() -> studentInfoController.assembleStudentsWithMapping(students), Collections.<Map<String, Object>>emptyList()));

        // 3. institutes — filter to the user's mapped set.
        out.put("institutes", safeCall(() -> queryInstitutes(scope), Collections.<InstituteDetail>emptyList()));

        // 4. counsellors — DISTINCT counsellors who have at least one appointment
        //    with a student matching the scope.
        out.put("counsellors", safeCall(() -> queryCounsellors(scope), Collections.<Counsellor>emptyList()));

        // 5. appointments — JOIN through student → studentInfo.
        out.put("appointments", safeCall(() -> queryAppointments(scope), Collections.<CounsellingAppointment>emptyList()));

        // 6. ratingSummary — GROUP BY counsellor over the scoped ratings.
        out.put("ratingSummary", safeCall(() -> queryRatingSummary(scope), Collections.<Map<String, Object>>emptyList()));

        // 7. assessments — DISTINCT assessments mapped to the user's institute(s).
        out.put("assessments", safeCall(() -> queryAssessments(scope), Collections.<AssessmentTable>emptyList()));

        // 8. reports — JOIN through user-student → studentInfo.
        out.put("reports", safeCall(() -> queryReports(scope), Collections.<GeneratedReport>emptyList()));
    }

    // ─── Scoped queries: implementations ─────────────────────────────────

    /** {@code students}: StudentInfo carries all 4 dims as direct columns. */
    private List<StudentInfo> queryStudents(AccessScope scope) {
        StringBuilder jpql = new StringBuilder("SELECT si FROM StudentInfo si WHERE ");
        Map<String, Object> params = new HashMap<>();
        AccessScopeJpqlBuilder.appendScopePredicate(jpql, params, "s", scope,
                new Fields("si.instituteId", "si.sessionId", "si.courseCode", "si.schoolSectionId"));
        return runQuery(jpql.toString(), StudentInfo.class, params);
    }

    /**
     * {@code institutes}: the user's mapped institutes only, filtered by
     * {@code display = true} to match the legacy controller's
     * {@code getallInstituteDetail()} behaviour.
     */
    private List<InstituteDetail> queryInstitutes(AccessScope scope) {
        if (scope.getAllowedInstituteCodes().isEmpty()) return Collections.emptyList();
        TypedQuery<InstituteDetail> q = em.createQuery(
                "SELECT i FROM InstituteDetail i " +
                        "WHERE i.instituteCode IN :codes AND (i.display IS NULL OR i.display = TRUE)",
                InstituteDetail.class);
        q.setParameter("codes", scope.getAllowedInstituteCodes());
        return q.getResultList();
    }

    /**
     * {@code counsellors}: {@code Counsellor} carries no direct institute
     * attribution; scoped by "has at least one appointment with a student
     * in the user's institute/session/class/section". JOIN path:
     * appointment → student (UserStudent) → studentInfo.
     */
    private List<Counsellor> queryCounsellors(AccessScope scope) {
        StringBuilder jpql = new StringBuilder(
                "SELECT DISTINCT c FROM Counsellor c WHERE c.id IN (" +
                        "SELECT a.counsellor.id FROM CounsellingAppointment a " +
                        "WHERE a.counsellor IS NOT NULL AND ");
        Map<String, Object> params = new HashMap<>();
        AccessScopeJpqlBuilder.appendScopePredicate(jpql, params, "c", scope,
                new Fields("a.student.studentInfo.instituteId", "a.student.studentInfo.sessionId",
                        "a.student.studentInfo.courseCode", "a.student.studentInfo.schoolSectionId"));
        jpql.append(")");
        return runQuery(jpql.toString(), Counsellor.class, params);
    }

    /** {@code appointments}: JOIN through student → studentInfo. */
    private List<CounsellingAppointment> queryAppointments(AccessScope scope) {
        StringBuilder jpql = new StringBuilder("SELECT a FROM CounsellingAppointment a WHERE ");
        Map<String, Object> params = new HashMap<>();
        AccessScopeJpqlBuilder.appendScopePredicate(jpql, params, "a", scope,
                new Fields("a.student.studentInfo.instituteId", "a.student.studentInfo.sessionId",
                        "a.student.studentInfo.courseCode", "a.student.studentInfo.schoolSectionId"));
        return runQuery(jpql.toString(), CounsellingAppointment.class, params);
    }

    /**
     * {@code ratingSummary}: same JOIN path as appointments, then GROUP BY
     * counsellor. Returns the {@code [{counsellorId, count, average}, ...]}
     * shape the FE expects.
     */
    private List<Map<String, Object>> queryRatingSummary(AccessScope scope) {
        StringBuilder jpql = new StringBuilder(
                "SELECT r.counsellor.id, COUNT(r), AVG(r.rating) FROM CounsellingRating r " +
                        "WHERE r.counsellor IS NOT NULL AND ");
        Map<String, Object> params = new HashMap<>();
        AccessScopeJpqlBuilder.appendScopePredicate(jpql, params, "rs", scope,
                new Fields("r.student.studentInfo.instituteId", "r.student.studentInfo.sessionId",
                        "r.student.studentInfo.courseCode", "r.student.studentInfo.schoolSectionId"));
        jpql.append(" GROUP BY r.counsellor.id");
        TypedQuery<Object[]> q = em.createQuery(jpql.toString(), Object[].class);
        params.forEach(q::setParameter);
        return mapRatingRows(q.getResultList());
    }

    /**
     * {@code assessments}: DISTINCT assessments whose
     * {@code AssessmentInstituteMapping} matches the user's scope. Uses the
     * full 4-dim predicate against the mapping row's own institute/session/
     * class/section columns.
     */
    private List<AssessmentTable> queryAssessments(AccessScope scope) {
        // AssessmentTable's JPA field is `id` (mapped to DB column assessment_id) —
        // JPQL resolves Java field names, not column names. AssessmentInstituteMapping
        // does have a distinct `assessmentId` Java field, so the inner subquery is
        // correct as written.
        StringBuilder jpql = new StringBuilder(
                "SELECT DISTINCT a FROM AssessmentTable a WHERE a.id IN (" +
                        "SELECT m.assessmentId FROM AssessmentInstituteMapping m " +
                        "WHERE (m.isActive IS NULL OR m.isActive = TRUE) AND ");
        Map<String, Object> params = new HashMap<>();
        AccessScopeJpqlBuilder.appendScopePredicate(jpql, params, "asm", scope,
                new Fields("m.instituteCode", "m.sessionId", "m.classId", "m.sectionId"));
        jpql.append(")");
        return runQuery(jpql.toString(), AssessmentTable.class, params);
    }

    /**
     * {@code reports}: JOIN {@code report.userStudent → studentInfo}; same
     * institute/session/class/section dims as appointments.
     */
    private List<GeneratedReport> queryReports(AccessScope scope) {
        StringBuilder jpql = new StringBuilder("SELECT r FROM GeneratedReport r WHERE ");
        Map<String, Object> params = new HashMap<>();
        AccessScopeJpqlBuilder.appendScopePredicate(jpql, params, "rp", scope,
                new Fields("r.userStudent.studentInfo.instituteId", "r.userStudent.studentInfo.sessionId",
                        "r.userStudent.studentInfo.courseCode", "r.userStudent.studentInfo.schoolSectionId"));
        return runQuery(jpql.toString(), GeneratedReport.class, params);
    }

    // ─── helpers ────────────────────────────────────────────────────────

    private <T> List<T> runQuery(String jpql, Class<T> resultClass, Map<String, Object> params) {
        TypedQuery<T> q = em.createQuery(jpql, resultClass);
        params.forEach(q::setParameter);
        return q.getResultList();
    }

    /** Convert {@code [counsellorId, count, avgRating]} rows to the FE shape. */
    private List<Map<String, Object>> mapRatingRows(List<Object[]> rows) {
        List<Map<String, Object>> out = new ArrayList<>(rows.size());
        for (Object[] row : rows) {
            Map<String, Object> m = new HashMap<>();
            m.put("counsellorId", row[0]);
            m.put("count", row[1] == null ? 0L : ((Number) row[1]).longValue());
            m.put("average", row[2] == null ? 0.0 : ((Number) row[2]).doubleValue());
            out.add(m);
        }
        return out;
    }

    private void stampScopeMeta(Map<String, Object> out, AccessScope scope) {
        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("allowedInstituteCodes", new ArrayList<>(scope.getAllowedInstituteCodes()));
        meta.put("ruleCount", scope.getRules().size());
        out.put("__accessScope", meta);
    }

    /** Per-list defensive wrapper — one failing list never strands the others. */
    private interface CallableSafe<T> { T call(); }
    private <T> T safeCall(CallableSafe<T> c, T fallback) {
        try {
            return c.call();
        } catch (Exception e) {
            log.warn("DashboardDataService: list query failed, returning fallback", e);
            return fallback;
        }
    }
}
