export var webcamphoto = { name: "Webcamphoto", variable: "webcam_photo" };

export var list_of_Document = [
  {
    name: "Qualified Rank",
    variable: "qualifiedRankLetter",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "qualifiedRankLetterPhysical",
  },
  {
    name: "Candidate's Photograph",
    variable: "studentPhotograph",
    required: true,
    type: "jpeg",
    filesize: "50",
    physicalVariable: "studentPhotographPhysical",
  },
  {
    name: "Aadhar Card",
    variable: "aadharCard",
    required: true,
    type: "pdf",
    filesize: "500",
    physicalVariable: "aadharCardPhysical",
  },
  {
    name: "Candidate's Signature",
    variable: "studentSignature",
    required: true,
    type: "jpeg",
    filesize: "50",
    physicalVariable: "studentSignaturePhysical",
  },
  {
    name: "Candidate's Thumb (Left-Hand) Impression ",
    variable: "studentThumbImpression",
    required: true,
    type: "jpeg",
    filesize: "50",
    physicalVariable: "studentThumbImpressionPhysical",
  },
  {
    name: "10th Marks Sheet",
    variable: "highSchoolMarksheet",
    required: true,
    type: "pdf",
    filesize: "500",
    physicalVariable: "highSchoolMarksheetPhysical",
  },
  {
    name: "10th Certificate",
    variable: "highSchoolCertificate",
    required: true,
    type: "pdf",
    filesize: "500",
    physicalVariable: "highSchoolCertificatePhysical",
  },
  {
    name: "12th Mark Sheet",
    variable: "intermediateMarksheet",
    required: true,
    type: "pdf",
    filesize: "500",
    physicalVariable: "intermediateMarksheetPhysical",
  },
  {
    name: "12th Certificate",
    variable: "intermediateCertificate",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "intermediateCertificatePhysical",
  },
  {
    name: "Transfer Certificate",
    variable: "transferCertificate",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "transferCertificatePhysical",
  },
  {
    name: "Migration Certificate",
    variable: "migrationCertificate",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "migrationCertificatePhysical",
  },
  {
    name: "Allotment Letter",
    variable: "allotmentLetter",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "allotmentLetterPhysical",
  },
  {
    name: "Affidavit For Gap on Rs 10/- Stamp Paper",
    variable: "affidavitForGap",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "affidavitForGapPhysical",
  },
  {
    name: "Domicile Certificate",
    variable: "domicileCertificateUp",
    required: true,
    type: "pdf",
    filesize: "500",
    physicalVariable: "domicileCertificateUpPhysical",
  },
  {
    name: "Cast Certificate",
    variable: "casteCertificate",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "casteCertificatePhysical",
  },
  {
    name: "Income Certificate",
    variable: "incomeCertificate",
    required: false,
    type: "pdf",
    filesize: "500",
    physicalVariable: "incomeCertificatePhysical",
  },
];
